export interface CityEntry {
  city: string;
  state: string;
  country: string;
  countryCode: string;
}

export const CITIES_DATA: CityEntry[] = [
  // ──── United States ────
  { city: "New York", state: "NY", country: "United States", countryCode: "US" },
  { city: "Los Angeles", state: "CA", country: "United States", countryCode: "US" },
  { city: "Chicago", state: "IL", country: "United States", countryCode: "US" },
  { city: "Houston", state: "TX", country: "United States", countryCode: "US" },
  { city: "Phoenix", state: "AZ", country: "United States", countryCode: "US" },
  { city: "Philadelphia", state: "PA", country: "United States", countryCode: "US" },
  { city: "San Antonio", state: "TX", country: "United States", countryCode: "US" },
  { city: "San Diego", state: "CA", country: "United States", countryCode: "US" },
  { city: "Dallas", state: "TX", country: "United States", countryCode: "US" },
  { city: "San Jose", state: "CA", country: "United States", countryCode: "US" },
  { city: "Austin", state: "TX", country: "United States", countryCode: "US" },
  { city: "Jacksonville", state: "FL", country: "United States", countryCode: "US" },
  { city: "Fort Worth", state: "TX", country: "United States", countryCode: "US" },
  { city: "Columbus", state: "OH", country: "United States", countryCode: "US" },
  { city: "Charlotte", state: "NC", country: "United States", countryCode: "US" },
  { city: "San Francisco", state: "CA", country: "United States", countryCode: "US" },
  { city: "Indianapolis", state: "IN", country: "United States", countryCode: "US" },
  { city: "Seattle", state: "WA", country: "United States", countryCode: "US" },
  { city: "Denver", state: "CO", country: "United States", countryCode: "US" },
  { city: "Washington", state: "DC", country: "United States", countryCode: "US" },
  { city: "Nashville", state: "TN", country: "United States", countryCode: "US" },
  { city: "Oklahoma City", state: "OK", country: "United States", countryCode: "US" },
  { city: "El Paso", state: "TX", country: "United States", countryCode: "US" },
  { city: "Boston", state: "MA", country: "United States", countryCode: "US" },
  { city: "Portland", state: "OR", country: "United States", countryCode: "US" },
  { city: "Las Vegas", state: "NV", country: "United States", countryCode: "US" },
  { city: "Memphis", state: "TN", country: "United States", countryCode: "US" },
  { city: "Louisville", state: "KY", country: "United States", countryCode: "US" },
  { city: "Baltimore", state: "MD", country: "United States", countryCode: "US" },
  { city: "Milwaukee", state: "WI", country: "United States", countryCode: "US" },
  { city: "Albuquerque", state: "NM", country: "United States", countryCode: "US" },
  { city: "Tucson", state: "AZ", country: "United States", countryCode: "US" },
  { city: "Fresno", state: "CA", country: "United States", countryCode: "US" },
  { city: "Sacramento", state: "CA", country: "United States", countryCode: "US" },
  { city: "Mesa", state: "AZ", country: "United States", countryCode: "US" },
  { city: "Kansas City", state: "MO", country: "United States", countryCode: "US" },
  { city: "Atlanta", state: "GA", country: "United States", countryCode: "US" },
  { city: "Omaha", state: "NE", country: "United States", countryCode: "US" },
  { city: "Colorado Springs", state: "CO", country: "United States", countryCode: "US" },
  { city: "Raleigh", state: "NC", country: "United States", countryCode: "US" },
  { city: "Virginia Beach", state: "VA", country: "United States", countryCode: "US" },
  { city: "Long Beach", state: "CA", country: "United States", countryCode: "US" },
  { city: "Miami", state: "FL", country: "United States", countryCode: "US" },
  { city: "Oakland", state: "CA", country: "United States", countryCode: "US" },
  { city: "Minneapolis", state: "MN", country: "United States", countryCode: "US" },
  { city: "Tulsa", state: "OK", country: "United States", countryCode: "US" },
  { city: "Tampa", state: "FL", country: "United States", countryCode: "US" },
  { city: "Arlington", state: "TX", country: "United States", countryCode: "US" },
  { city: "New Orleans", state: "LA", country: "United States", countryCode: "US" },
  { city: "Wichita", state: "KS", country: "United States", countryCode: "US" },
  { city: "Cleveland", state: "OH", country: "United States", countryCode: "US" },
  { city: "Bakersfield", state: "CA", country: "United States", countryCode: "US" },
  { city: "Aurora", state: "CO", country: "United States", countryCode: "US" },
  { city: "Anaheim", state: "CA", country: "United States", countryCode: "US" },
  { city: "Honolulu", state: "HI", country: "United States", countryCode: "US" },
  { city: "Santa Ana", state: "CA", country: "United States", countryCode: "US" },
  { city: "Riverside", state: "CA", country: "United States", countryCode: "US" },
  { city: "Corpus Christi", state: "TX", country: "United States", countryCode: "US" },
  { city: "Lexington", state: "KY", country: "United States", countryCode: "US" },
  { city: "Stockton", state: "CA", country: "United States", countryCode: "US" },
  { city: "Pittsburgh", state: "PA", country: "United States", countryCode: "US" },
  { city: "Saint Paul", state: "MN", country: "United States", countryCode: "US" },
  { city: "Anchorage", state: "AK", country: "United States", countryCode: "US" },
  { city: "Cincinnati", state: "OH", country: "United States", countryCode: "US" },
  { city: "Henderson", state: "NV", country: "United States", countryCode: "US" },
  { city: "Greensboro", state: "NC", country: "United States", countryCode: "US" },
  { city: "Plano", state: "TX", country: "United States", countryCode: "US" },
  { city: "Newark", state: "NJ", country: "United States", countryCode: "US" },
  { city: "Lincoln", state: "NE", country: "United States", countryCode: "US" },
  { city: "Orlando", state: "FL", country: "United States", countryCode: "US" },
  { city: "Irvine", state: "CA", country: "United States", countryCode: "US" },
  { city: "Toledo", state: "OH", country: "United States", countryCode: "US" },
  { city: "Jersey City", state: "NJ", country: "United States", countryCode: "US" },
  { city: "Chula Vista", state: "CA", country: "United States", countryCode: "US" },
  { city: "Durham", state: "NC", country: "United States", countryCode: "US" },
  { city: "Laredo", state: "TX", country: "United States", countryCode: "US" },
  { city: "Madison", state: "WI", country: "United States", countryCode: "US" },
  { city: "Gilbert", state: "AZ", country: "United States", countryCode: "US" },
  { city: "Norfolk", state: "VA", country: "United States", countryCode: "US" },
  { city: "Reno", state: "NV", country: "United States", countryCode: "US" },
  { city: "Winston-Salem", state: "NC", country: "United States", countryCode: "US" },
  { city: "Glendale", state: "AZ", country: "United States", countryCode: "US" },
  { city: "Hialeah", state: "FL", country: "United States", countryCode: "US" },
  { city: "Garland", state: "TX", country: "United States", countryCode: "US" },
  { city: "Scottsdale", state: "AZ", country: "United States", countryCode: "US" },
  { city: "Irving", state: "TX", country: "United States", countryCode: "US" },
  { city: "Chesapeake", state: "VA", country: "United States", countryCode: "US" },
  { city: "North Las Vegas", state: "NV", country: "United States", countryCode: "US" },
  { city: "Fremont", state: "CA", country: "United States", countryCode: "US" },
  { city: "Richmond", state: "VA", country: "United States", countryCode: "US" },
  { city: "Boise", state: "ID", country: "United States", countryCode: "US" },
  { city: "San Bernardino", state: "CA", country: "United States", countryCode: "US" },
  { city: "Spokane", state: "WA", country: "United States", countryCode: "US" },
  { city: "Birmingham", state: "AL", country: "United States", countryCode: "US" },
  { city: "Rochester", state: "NY", country: "United States", countryCode: "US" },
  { city: "Des Moines", state: "IA", country: "United States", countryCode: "US" },
  { city: "Montgomery", state: "AL", country: "United States", countryCode: "US" },
  { city: "Modesto", state: "CA", country: "United States", countryCode: "US" },
  { city: "Fayetteville", state: "NC", country: "United States", countryCode: "US" },
  { city: "Tacoma", state: "WA", country: "United States", countryCode: "US" },
  { city: "Shreveport", state: "LA", country: "United States", countryCode: "US" },
  { city: "Fontana", state: "CA", country: "United States", countryCode: "US" },
  { city: "Moreno Valley", state: "CA", country: "United States", countryCode: "US" },
  { city: "Akron", state: "OH", country: "United States", countryCode: "US" },
  { city: "Yonkers", state: "NY", country: "United States", countryCode: "US" },
  { city: "Columbus", state: "GA", country: "United States", countryCode: "US" },
  { city: "Little Rock", state: "AR", country: "United States", countryCode: "US" },
  { city: "Amarillo", state: "TX", country: "United States", countryCode: "US" },
  { city: "Huntsville", state: "AL", country: "United States", countryCode: "US" },
  { city: "Grand Rapids", state: "MI", country: "United States", countryCode: "US" },
  { city: "Salt Lake City", state: "UT", country: "United States", countryCode: "US" },
  { city: "Tallahassee", state: "FL", country: "United States", countryCode: "US" },
  { city: "Worcester", state: "MA", country: "United States", countryCode: "US" },
  { city: "Newport News", state: "VA", country: "United States", countryCode: "US" },
  { city: "Knoxville", state: "TN", country: "United States", countryCode: "US" },
  { city: "Providence", state: "RI", country: "United States", countryCode: "US" },
  { city: "Santa Clarita", state: "CA", country: "United States", countryCode: "US" },
  { city: "Fort Collins", state: "CO", country: "United States", countryCode: "US" },
  { city: "Chattanooga", state: "TN", country: "United States", countryCode: "US" },
  { city: "Tempe", state: "AZ", country: "United States", countryCode: "US" },
  { city: "Brownsville", state: "TX", country: "United States", countryCode: "US" },
  { city: "Wilmington", state: "NC", country: "United States", countryCode: "US" },
  { city: "Wilmington", state: "DE", country: "United States", countryCode: "US" },
  { city: "Shallotte", state: "NC", country: "United States", countryCode: "US" },
  { city: "Leland", state: "NC", country: "United States", countryCode: "US" },
  { city: "Southport", state: "NC", country: "United States", countryCode: "US" },
  { city: "Wrightsville Beach", state: "NC", country: "United States", countryCode: "US" },
  { city: "Carolina Beach", state: "NC", country: "United States", countryCode: "US" },
  { city: "Jacksonville", state: "NC", country: "United States", countryCode: "US" },
  { city: "Asheville", state: "NC", country: "United States", countryCode: "US" },
  { city: "Greenville", state: "NC", country: "United States", countryCode: "US" },
  { city: "Gastonia", state: "NC", country: "United States", countryCode: "US" },
  { city: "High Point", state: "NC", country: "United States", countryCode: "US" },
  { city: "Concord", state: "NC", country: "United States", countryCode: "US" },
  { city: "Cary", state: "NC", country: "United States", countryCode: "US" },
  { city: "Apex", state: "NC", country: "United States", countryCode: "US" },
  { city: "Chapel Hill", state: "NC", country: "United States", countryCode: "US" },
  { city: "Huntersville", state: "NC", country: "United States", countryCode: "US" },
  { city: "Mooresville", state: "NC", country: "United States", countryCode: "US" },
  { city: "Rocky Mount", state: "NC", country: "United States", countryCode: "US" },
  { city: "Burlington", state: "NC", country: "United States", countryCode: "US" },
  { city: "Hickory", state: "NC", country: "United States", countryCode: "US" },
  { city: "Kannapolis", state: "NC", country: "United States", countryCode: "US" },
  { city: "New Bern", state: "NC", country: "United States", countryCode: "US" },
  { city: "Sanford", state: "NC", country: "United States", countryCode: "US" },
  { city: "Wake Forest", state: "NC", country: "United States", countryCode: "US" },
  { city: "Detroit", state: "MI", country: "United States", countryCode: "US" },
  { city: "Buffalo", state: "NY", country: "United States", countryCode: "US" },
  { city: "Hartford", state: "CT", country: "United States", countryCode: "US" },
  { city: "Bridgeport", state: "CT", country: "United States", countryCode: "US" },
  { city: "New Haven", state: "CT", country: "United States", countryCode: "US" },
  { city: "Stamford", state: "CT", country: "United States", countryCode: "US" },
  { city: "Manchester", state: "NH", country: "United States", countryCode: "US" },
  { city: "Burlington", state: "VT", country: "United States", countryCode: "US" },
  { city: "Portland", state: "ME", country: "United States", countryCode: "US" },
  { city: "Savannah", state: "GA", country: "United States", countryCode: "US" },
  { city: "Augusta", state: "GA", country: "United States", countryCode: "US" },
  { city: "Charleston", state: "SC", country: "United States", countryCode: "US" },
  { city: "Columbia", state: "SC", country: "United States", countryCode: "US" },
  { city: "Greenville", state: "SC", country: "United States", countryCode: "US" },
  { city: "Myrtle Beach", state: "SC", country: "United States", countryCode: "US" },
  { city: "St. Petersburg", state: "FL", country: "United States", countryCode: "US" },
  { city: "Fort Lauderdale", state: "FL", country: "United States", countryCode: "US" },
  { city: "Sarasota", state: "FL", country: "United States", countryCode: "US" },
  { city: "Fort Myers", state: "FL", country: "United States", countryCode: "US" },
  { city: "Gainesville", state: "FL", country: "United States", countryCode: "US" },
  { city: "Pensacola", state: "FL", country: "United States", countryCode: "US" },
  { city: "Naples", state: "FL", country: "United States", countryCode: "US" },
  { city: "West Palm Beach", state: "FL", country: "United States", countryCode: "US" },
  { city: "Boca Raton", state: "FL", country: "United States", countryCode: "US" },
  { city: "Daytona Beach", state: "FL", country: "United States", countryCode: "US" },
  { city: "Lubbock", state: "TX", country: "United States", countryCode: "US" },
  { city: "Midland", state: "TX", country: "United States", countryCode: "US" },
  { city: "McAllen", state: "TX", country: "United States", countryCode: "US" },
  { city: "Beaumont", state: "TX", country: "United States", countryCode: "US" },
  { city: "Abilene", state: "TX", country: "United States", countryCode: "US" },
  { city: "Waco", state: "TX", country: "United States", countryCode: "US" },
  { city: "Provo", state: "UT", country: "United States", countryCode: "US" },
  { city: "Ogden", state: "UT", country: "United States", countryCode: "US" },
  { city: "Billings", state: "MT", country: "United States", countryCode: "US" },
  { city: "Missoula", state: "MT", country: "United States", countryCode: "US" },
  { city: "Cheyenne", state: "WY", country: "United States", countryCode: "US" },
  { city: "Fargo", state: "ND", country: "United States", countryCode: "US" },
  { city: "Sioux Falls", state: "SD", country: "United States", countryCode: "US" },
  { city: "Rapid City", state: "SD", country: "United States", countryCode: "US" },
  { city: "Bismarck", state: "ND", country: "United States", countryCode: "US" },
  { city: "Columbia", state: "MO", country: "United States", countryCode: "US" },
  { city: "Springfield", state: "MO", country: "United States", countryCode: "US" },
  { city: "Springfield", state: "IL", country: "United States", countryCode: "US" },
  { city: "Peoria", state: "IL", country: "United States", countryCode: "US" },
  { city: "Naperville", state: "IL", country: "United States", countryCode: "US" },
  { city: "Evanston", state: "IL", country: "United States", countryCode: "US" },
  { city: "Topeka", state: "KS", country: "United States", countryCode: "US" },
  { city: "Overland Park", state: "KS", country: "United States", countryCode: "US" },
  { city: "Jackson", state: "MS", country: "United States", countryCode: "US" },
  { city: "Mobile", state: "AL", country: "United States", countryCode: "US" },
  { city: "Baton Rouge", state: "LA", country: "United States", countryCode: "US" },
  { city: "Santa Fe", state: "NM", country: "United States", countryCode: "US" },
  { city: "Las Cruces", state: "NM", country: "United States", countryCode: "US" },
  { city: "Flagstaff", state: "AZ", country: "United States", countryCode: "US" },
  { city: "Eugene", state: "OR", country: "United States", countryCode: "US" },
  { city: "Salem", state: "OR", country: "United States", countryCode: "US" },
  { city: "Bend", state: "OR", country: "United States", countryCode: "US" },

  // ──── Central America ────
  { city: "Guatemala City", state: "Guatemala", country: "Guatemala", countryCode: "GT" },
  { city: "Antigua Guatemala", state: "Sacatepéquez", country: "Guatemala", countryCode: "GT" },
  { city: "Quetzaltenango", state: "Quetzaltenango", country: "Guatemala", countryCode: "GT" },
  { city: "Escuintla", state: "Escuintla", country: "Guatemala", countryCode: "GT" },
  { city: "Mixco", state: "Guatemala", country: "Guatemala", countryCode: "GT" },
  { city: "Villa Nueva", state: "Guatemala", country: "Guatemala", countryCode: "GT" },
  { city: "Belize City", state: "Belize", country: "Belize", countryCode: "BZ" },
  { city: "Belmopan", state: "Cayo", country: "Belize", countryCode: "BZ" },
  { city: "San Ignacio", state: "Cayo", country: "Belize", countryCode: "BZ" },
  { city: "San Pedro", state: "Ambergris Caye", country: "Belize", countryCode: "BZ" },
  { city: "Tegucigalpa", state: "Francisco Morazán", country: "Honduras", countryCode: "HN" },
  { city: "San Pedro Sula", state: "Cortés", country: "Honduras", countryCode: "HN" },
  { city: "La Ceiba", state: "Atlántida", country: "Honduras", countryCode: "HN" },
  { city: "Roatán", state: "Islas de la Bahía", country: "Honduras", countryCode: "HN" },
  { city: "San Salvador", state: "San Salvador", country: "El Salvador", countryCode: "SV" },
  { city: "Santa Ana", state: "Santa Ana", country: "El Salvador", countryCode: "SV" },
  { city: "San Miguel", state: "San Miguel", country: "El Salvador", countryCode: "SV" },
  { city: "Managua", state: "Managua", country: "Nicaragua", countryCode: "NI" },
  { city: "León", state: "León", country: "Nicaragua", countryCode: "NI" },
  { city: "Granada", state: "Granada", country: "Nicaragua", countryCode: "NI" },
  { city: "San Juan del Sur", state: "Rivas", country: "Nicaragua", countryCode: "NI" },
  { city: "San José", state: "San José", country: "Costa Rica", countryCode: "CR" },
  { city: "Alajuela", state: "Alajuela", country: "Costa Rica", countryCode: "CR" },
  { city: "Heredia", state: "Heredia", country: "Costa Rica", countryCode: "CR" },
  { city: "Liberia", state: "Guanacaste", country: "Costa Rica", countryCode: "CR" },
  { city: "Puerto Limón", state: "Limón", country: "Costa Rica", countryCode: "CR" },
  { city: "Cartago", state: "Cartago", country: "Costa Rica", countryCode: "CR" },
  { city: "Tamarindo", state: "Guanacaste", country: "Costa Rica", countryCode: "CR" },
  { city: "Panama City", state: "Panamá", country: "Panama", countryCode: "PA" },
  { city: "Colón", state: "Colón", country: "Panama", countryCode: "PA" },
  { city: "David", state: "Chiriquí", country: "Panama", countryCode: "PA" },
  { city: "Bocas del Toro", state: "Bocas del Toro", country: "Panama", countryCode: "PA" },

  // ──── Caribbean ────
  { city: "San Juan", state: "PR", country: "Puerto Rico", countryCode: "PR" },
  { city: "Ponce", state: "PR", country: "Puerto Rico", countryCode: "PR" },
  { city: "Bayamón", state: "PR", country: "Puerto Rico", countryCode: "PR" },
  { city: "Carolina", state: "PR", country: "Puerto Rico", countryCode: "PR" },
  { city: "Mayagüez", state: "PR", country: "Puerto Rico", countryCode: "PR" },
  { city: "Caguas", state: "PR", country: "Puerto Rico", countryCode: "PR" },
  { city: "Kingston", state: "Kingston", country: "Jamaica", countryCode: "JM" },
  { city: "Montego Bay", state: "St. James", country: "Jamaica", countryCode: "JM" },
  { city: "Ocho Rios", state: "St. Ann", country: "Jamaica", countryCode: "JM" },
  { city: "Negril", state: "Westmoreland", country: "Jamaica", countryCode: "JM" },
  { city: "Spanish Town", state: "St. Catherine", country: "Jamaica", countryCode: "JM" },
  { city: "Santo Domingo", state: "Distrito Nacional", country: "Dominican Republic", countryCode: "DO" },
  { city: "Santiago", state: "Santiago", country: "Dominican Republic", countryCode: "DO" },
  { city: "Punta Cana", state: "La Altagracia", country: "Dominican Republic", countryCode: "DO" },
  { city: "Puerto Plata", state: "Puerto Plata", country: "Dominican Republic", countryCode: "DO" },
  { city: "Port of Spain", state: "Port of Spain", country: "Trinidad and Tobago", countryCode: "TT" },
  { city: "San Fernando", state: "San Fernando", country: "Trinidad and Tobago", countryCode: "TT" },
  { city: "Chaguanas", state: "Chaguanas", country: "Trinidad and Tobago", countryCode: "TT" },
  { city: "Scarborough", state: "Tobago", country: "Trinidad and Tobago", countryCode: "TT" },
  { city: "Bridgetown", state: "St. Michael", country: "Barbados", countryCode: "BB" },
  { city: "Speightstown", state: "St. Peter", country: "Barbados", countryCode: "BB" },
  { city: "Nassau", state: "New Providence", country: "Bahamas", countryCode: "BS" },
  { city: "Freeport", state: "Grand Bahama", country: "Bahamas", countryCode: "BS" },
  { city: "Marsh Harbour", state: "Abaco", country: "Bahamas", countryCode: "BS" },
  { city: "Havana", state: "Havana", country: "Cuba", countryCode: "CU" },
  { city: "Santiago de Cuba", state: "Santiago de Cuba", country: "Cuba", countryCode: "CU" },
  { city: "Varadero", state: "Matanzas", country: "Cuba", countryCode: "CU" },
  { city: "Trinidad", state: "Sancti Spíritus", country: "Cuba", countryCode: "CU" },
  { city: "Camagüey", state: "Camagüey", country: "Cuba", countryCode: "CU" },
  { city: "Port-au-Prince", state: "Ouest", country: "Haiti", countryCode: "HT" },
  { city: "Cap-Haïtien", state: "Nord", country: "Haiti", countryCode: "HT" },
  { city: "Castries", state: "Castries", country: "Saint Lucia", countryCode: "LC" },
  { city: "Roseau", state: "St. George", country: "Dominica", countryCode: "DM" },
  { city: "St. George's", state: "St. George", country: "Grenada", countryCode: "GD" },
  { city: "Kingstown", state: "St. George", country: "Saint Vincent", countryCode: "VC" },
  { city: "Basseterre", state: "St. George", country: "Saint Kitts and Nevis", countryCode: "KN" },
  { city: "St. John's", state: "St. John", country: "Antigua and Barbuda", countryCode: "AG" },
  { city: "Willemstad", state: "Curaçao", country: "Curaçao", countryCode: "CW" },
  { city: "Oranjestad", state: "Aruba", country: "Aruba", countryCode: "AW" },
  { city: "Philipsburg", state: "Sint Maarten", country: "Sint Maarten", countryCode: "SX" },
  { city: "George Town", state: "Grand Cayman", country: "Cayman Islands", countryCode: "KY" },
  { city: "Hamilton", state: "Pembroke", country: "Bermuda", countryCode: "BM" },
  { city: "Road Town", state: "Tortola", country: "British Virgin Islands", countryCode: "VG" },
  { city: "Charlotte Amalie", state: "St. Thomas", country: "US Virgin Islands", countryCode: "VI" },

  // ──── Europe ────
  { city: "London", state: "England", country: "United Kingdom", countryCode: "GB" },
  { city: "Manchester", state: "England", country: "United Kingdom", countryCode: "GB" },
  { city: "Birmingham", state: "England", country: "United Kingdom", countryCode: "GB" },
  { city: "Liverpool", state: "England", country: "United Kingdom", countryCode: "GB" },
  { city: "Edinburgh", state: "Scotland", country: "United Kingdom", countryCode: "GB" },
  { city: "Glasgow", state: "Scotland", country: "United Kingdom", countryCode: "GB" },
  { city: "Bristol", state: "England", country: "United Kingdom", countryCode: "GB" },
  { city: "Leeds", state: "England", country: "United Kingdom", countryCode: "GB" },
  { city: "Cardiff", state: "Wales", country: "United Kingdom", countryCode: "GB" },
  { city: "Belfast", state: "Northern Ireland", country: "United Kingdom", countryCode: "GB" },
  { city: "Paris", state: "Île-de-France", country: "France", countryCode: "FR" },
  { city: "Marseille", state: "PACA", country: "France", countryCode: "FR" },
  { city: "Lyon", state: "Auvergne-Rhône-Alpes", country: "France", countryCode: "FR" },
  { city: "Toulouse", state: "Occitanie", country: "France", countryCode: "FR" },
  { city: "Nice", state: "PACA", country: "France", countryCode: "FR" },
  { city: "Bordeaux", state: "Nouvelle-Aquitaine", country: "France", countryCode: "FR" },
  { city: "Strasbourg", state: "Grand Est", country: "France", countryCode: "FR" },
  { city: "Berlin", state: "Berlin", country: "Germany", countryCode: "DE" },
  { city: "Munich", state: "Bavaria", country: "Germany", countryCode: "DE" },
  { city: "Hamburg", state: "Hamburg", country: "Germany", countryCode: "DE" },
  { city: "Frankfurt", state: "Hesse", country: "Germany", countryCode: "DE" },
  { city: "Cologne", state: "NRW", country: "Germany", countryCode: "DE" },
  { city: "Stuttgart", state: "Baden-Württemberg", country: "Germany", countryCode: "DE" },
  { city: "Düsseldorf", state: "NRW", country: "Germany", countryCode: "DE" },
  { city: "Leipzig", state: "Saxony", country: "Germany", countryCode: "DE" },
  { city: "Madrid", state: "Madrid", country: "Spain", countryCode: "ES" },
  { city: "Barcelona", state: "Catalonia", country: "Spain", countryCode: "ES" },
  { city: "Valencia", state: "Valencia", country: "Spain", countryCode: "ES" },
  { city: "Seville", state: "Andalusia", country: "Spain", countryCode: "ES" },
  { city: "Malaga", state: "Andalusia", country: "Spain", countryCode: "ES" },
  { city: "Bilbao", state: "Basque Country", country: "Spain", countryCode: "ES" },
  { city: "Rome", state: "Lazio", country: "Italy", countryCode: "IT" },
  { city: "Milan", state: "Lombardy", country: "Italy", countryCode: "IT" },
  { city: "Naples", state: "Campania", country: "Italy", countryCode: "IT" },
  { city: "Turin", state: "Piedmont", country: "Italy", countryCode: "IT" },
  { city: "Florence", state: "Tuscany", country: "Italy", countryCode: "IT" },
  { city: "Venice", state: "Veneto", country: "Italy", countryCode: "IT" },
  { city: "Bologna", state: "Emilia-Romagna", country: "Italy", countryCode: "IT" },
  { city: "Lisbon", state: "Lisboa", country: "Portugal", countryCode: "PT" },
  { city: "Porto", state: "Porto", country: "Portugal", countryCode: "PT" },
  { city: "Faro", state: "Algarve", country: "Portugal", countryCode: "PT" },
  { city: "Amsterdam", state: "North Holland", country: "Netherlands", countryCode: "NL" },
  { city: "Rotterdam", state: "South Holland", country: "Netherlands", countryCode: "NL" },
  { city: "The Hague", state: "South Holland", country: "Netherlands", countryCode: "NL" },
  { city: "Utrecht", state: "Utrecht", country: "Netherlands", countryCode: "NL" },
  { city: "Brussels", state: "Brussels", country: "Belgium", countryCode: "BE" },
  { city: "Antwerp", state: "Flanders", country: "Belgium", countryCode: "BE" },
  { city: "Ghent", state: "Flanders", country: "Belgium", countryCode: "BE" },
  { city: "Vienna", state: "Vienna", country: "Austria", countryCode: "AT" },
  { city: "Salzburg", state: "Salzburg", country: "Austria", countryCode: "AT" },
  { city: "Innsbruck", state: "Tyrol", country: "Austria", countryCode: "AT" },
  { city: "Zurich", state: "Zürich", country: "Switzerland", countryCode: "CH" },
  { city: "Geneva", state: "Geneva", country: "Switzerland", countryCode: "CH" },
  { city: "Bern", state: "Bern", country: "Switzerland", countryCode: "CH" },
  { city: "Basel", state: "Basel-Stadt", country: "Switzerland", countryCode: "CH" },
  { city: "Stockholm", state: "Stockholm", country: "Sweden", countryCode: "SE" },
  { city: "Gothenburg", state: "Västra Götaland", country: "Sweden", countryCode: "SE" },
  { city: "Malmö", state: "Skåne", country: "Sweden", countryCode: "SE" },
  { city: "Copenhagen", state: "Capital Region", country: "Denmark", countryCode: "DK" },
  { city: "Aarhus", state: "Central Denmark", country: "Denmark", countryCode: "DK" },
  { city: "Oslo", state: "Oslo", country: "Norway", countryCode: "NO" },
  { city: "Bergen", state: "Vestland", country: "Norway", countryCode: "NO" },
  { city: "Trondheim", state: "Trøndelag", country: "Norway", countryCode: "NO" },
  { city: "Helsinki", state: "Uusimaa", country: "Finland", countryCode: "FI" },
  { city: "Tampere", state: "Pirkanmaa", country: "Finland", countryCode: "FI" },
  { city: "Dublin", state: "Leinster", country: "Ireland", countryCode: "IE" },
  { city: "Cork", state: "Munster", country: "Ireland", countryCode: "IE" },
  { city: "Galway", state: "Connacht", country: "Ireland", countryCode: "IE" },
  { city: "Warsaw", state: "Masovia", country: "Poland", countryCode: "PL" },
  { city: "Krakow", state: "Lesser Poland", country: "Poland", countryCode: "PL" },
  { city: "Wroclaw", state: "Lower Silesia", country: "Poland", countryCode: "PL" },
  { city: "Gdansk", state: "Pomerania", country: "Poland", countryCode: "PL" },
  { city: "Prague", state: "Prague", country: "Czech Republic", countryCode: "CZ" },
  { city: "Brno", state: "South Moravia", country: "Czech Republic", countryCode: "CZ" },
  { city: "Budapest", state: "Budapest", country: "Hungary", countryCode: "HU" },
  { city: "Bucharest", state: "Bucharest", country: "Romania", countryCode: "RO" },
  { city: "Cluj-Napoca", state: "Cluj", country: "Romania", countryCode: "RO" },
  { city: "Sofia", state: "Sofia", country: "Bulgaria", countryCode: "BG" },
  { city: "Athens", state: "Attica", country: "Greece", countryCode: "GR" },
  { city: "Thessaloniki", state: "Central Macedonia", country: "Greece", countryCode: "GR" },
  { city: "Zagreb", state: "Zagreb", country: "Croatia", countryCode: "HR" },
  { city: "Split", state: "Split-Dalmatia", country: "Croatia", countryCode: "HR" },
  { city: "Dubrovnik", state: "Dubrovnik-Neretva", country: "Croatia", countryCode: "HR" },
  { city: "Belgrade", state: "Belgrade", country: "Serbia", countryCode: "RS" },
  { city: "Ljubljana", state: "Ljubljana", country: "Slovenia", countryCode: "SI" },
  { city: "Bratislava", state: "Bratislava", country: "Slovakia", countryCode: "SK" },
  { city: "Tallinn", state: "Harju", country: "Estonia", countryCode: "EE" },
  { city: "Riga", state: "Riga", country: "Latvia", countryCode: "LV" },
  { city: "Vilnius", state: "Vilnius", country: "Lithuania", countryCode: "LT" },
  { city: "Kyiv", state: "Kyiv", country: "Ukraine", countryCode: "UA" },
  { city: "Lviv", state: "Lviv Oblast", country: "Ukraine", countryCode: "UA" },
  { city: "Odesa", state: "Odesa Oblast", country: "Ukraine", countryCode: "UA" },
  { city: "Moscow", state: "Moscow", country: "Russia", countryCode: "RU" },
  { city: "Saint Petersburg", state: "Saint Petersburg", country: "Russia", countryCode: "RU" },
  { city: "Reykjavik", state: "Capital Region", country: "Iceland", countryCode: "IS" },
  { city: "Luxembourg City", state: "Luxembourg", country: "Luxembourg", countryCode: "LU" },
  { city: "Monaco", state: "Monaco", country: "Monaco", countryCode: "MC" },
  { city: "Valletta", state: "South Eastern", country: "Malta", countryCode: "MT" },
  { city: "Nicosia", state: "Nicosia", country: "Cyprus", countryCode: "CY" },
  { city: "Limassol", state: "Limassol", country: "Cyprus", countryCode: "CY" },
  { city: "Podgorica", state: "Podgorica", country: "Montenegro", countryCode: "ME" },
  { city: "Sarajevo", state: "Sarajevo", country: "Bosnia and Herzegovina", countryCode: "BA" },
  { city: "Skopje", state: "Skopje", country: "North Macedonia", countryCode: "MK" },
  { city: "Tirana", state: "Tirana", country: "Albania", countryCode: "AL" },

  // ──── South America ────
  { city: "São Paulo", state: "SP", country: "Brazil", countryCode: "BR" },
  { city: "Rio de Janeiro", state: "RJ", country: "Brazil", countryCode: "BR" },
  { city: "Brasília", state: "DF", country: "Brazil", countryCode: "BR" },
  { city: "Salvador", state: "BA", country: "Brazil", countryCode: "BR" },
  { city: "Fortaleza", state: "CE", country: "Brazil", countryCode: "BR" },
  { city: "Belo Horizonte", state: "MG", country: "Brazil", countryCode: "BR" },
  { city: "Curitiba", state: "PR", country: "Brazil", countryCode: "BR" },
  { city: "Recife", state: "PE", country: "Brazil", countryCode: "BR" },
  { city: "Manaus", state: "AM", country: "Brazil", countryCode: "BR" },
  { city: "Porto Alegre", state: "RS", country: "Brazil", countryCode: "BR" },
  { city: "Florianópolis", state: "SC", country: "Brazil", countryCode: "BR" },
  { city: "Buenos Aires", state: "CABA", country: "Argentina", countryCode: "AR" },
  { city: "Córdoba", state: "Córdoba", country: "Argentina", countryCode: "AR" },
  { city: "Rosario", state: "Santa Fe", country: "Argentina", countryCode: "AR" },
  { city: "Mendoza", state: "Mendoza", country: "Argentina", countryCode: "AR" },
  { city: "Bariloche", state: "Río Negro", country: "Argentina", countryCode: "AR" },
  { city: "Santiago", state: "Santiago", country: "Chile", countryCode: "CL" },
  { city: "Valparaíso", state: "Valparaíso", country: "Chile", countryCode: "CL" },
  { city: "Concepción", state: "Biobío", country: "Chile", countryCode: "CL" },
  { city: "Lima", state: "Lima", country: "Peru", countryCode: "PE" },
  { city: "Cusco", state: "Cusco", country: "Peru", countryCode: "PE" },
  { city: "Arequipa", state: "Arequipa", country: "Peru", countryCode: "PE" },
  { city: "Bogotá", state: "Cundinamarca", country: "Colombia", countryCode: "CO" },
  { city: "Medellín", state: "Antioquia", country: "Colombia", countryCode: "CO" },
  { city: "Cali", state: "Valle del Cauca", country: "Colombia", countryCode: "CO" },
  { city: "Cartagena", state: "Bolívar", country: "Colombia", countryCode: "CO" },
  { city: "Barranquilla", state: "Atlántico", country: "Colombia", countryCode: "CO" },
  { city: "Caracas", state: "Capital District", country: "Venezuela", countryCode: "VE" },
  { city: "Maracaibo", state: "Zulia", country: "Venezuela", countryCode: "VE" },
  { city: "Quito", state: "Pichincha", country: "Ecuador", countryCode: "EC" },
  { city: "Guayaquil", state: "Guayas", country: "Ecuador", countryCode: "EC" },
  { city: "Cuenca", state: "Azuay", country: "Ecuador", countryCode: "EC" },
  { city: "La Paz", state: "La Paz", country: "Bolivia", countryCode: "BO" },
  { city: "Santa Cruz", state: "Santa Cruz", country: "Bolivia", countryCode: "BO" },
  { city: "Cochabamba", state: "Cochabamba", country: "Bolivia", countryCode: "BO" },
  { city: "Asunción", state: "Asunción", country: "Paraguay", countryCode: "PY" },
  { city: "Montevideo", state: "Montevideo", country: "Uruguay", countryCode: "UY" },
  { city: "Punta del Este", state: "Maldonado", country: "Uruguay", countryCode: "UY" },
  { city: "Georgetown", state: "Demerara-Mahaica", country: "Guyana", countryCode: "GY" },
  { city: "Paramaribo", state: "Paramaribo", country: "Suriname", countryCode: "SR" },
  { city: "Cayenne", state: "Guyane", country: "French Guiana", countryCode: "GF" },

  // ──── Asia Pacific ────
  { city: "Tokyo", state: "Tokyo", country: "Japan", countryCode: "JP" },
  { city: "Osaka", state: "Osaka", country: "Japan", countryCode: "JP" },
  { city: "Kyoto", state: "Kyoto", country: "Japan", countryCode: "JP" },
  { city: "Yokohama", state: "Kanagawa", country: "Japan", countryCode: "JP" },
  { city: "Fukuoka", state: "Fukuoka", country: "Japan", countryCode: "JP" },
  { city: "Seoul", state: "Seoul", country: "South Korea", countryCode: "KR" },
  { city: "Busan", state: "Busan", country: "South Korea", countryCode: "KR" },
  { city: "Incheon", state: "Incheon", country: "South Korea", countryCode: "KR" },
  { city: "Beijing", state: "Beijing", country: "China", countryCode: "CN" },
  { city: "Shanghai", state: "Shanghai", country: "China", countryCode: "CN" },
  { city: "Shenzhen", state: "Guangdong", country: "China", countryCode: "CN" },
  { city: "Guangzhou", state: "Guangdong", country: "China", countryCode: "CN" },
  { city: "Chengdu", state: "Sichuan", country: "China", countryCode: "CN" },
  { city: "Hangzhou", state: "Zhejiang", country: "China", countryCode: "CN" },
  { city: "Wuhan", state: "Hubei", country: "China", countryCode: "CN" },
  { city: "Xi'an", state: "Shaanxi", country: "China", countryCode: "CN" },
  { city: "Hong Kong", state: "Hong Kong", country: "Hong Kong", countryCode: "HK" },
  { city: "Taipei", state: "Taipei", country: "Taiwan", countryCode: "TW" },
  { city: "Kaohsiung", state: "Kaohsiung", country: "Taiwan", countryCode: "TW" },
  { city: "Singapore", state: "Singapore", country: "Singapore", countryCode: "SG" },
  { city: "Bangkok", state: "Bangkok", country: "Thailand", countryCode: "TH" },
  { city: "Chiang Mai", state: "Chiang Mai", country: "Thailand", countryCode: "TH" },
  { city: "Phuket", state: "Phuket", country: "Thailand", countryCode: "TH" },
  { city: "Pattaya", state: "Chonburi", country: "Thailand", countryCode: "TH" },
  { city: "Kuala Lumpur", state: "KL", country: "Malaysia", countryCode: "MY" },
  { city: "Penang", state: "Penang", country: "Malaysia", countryCode: "MY" },
  { city: "Johor Bahru", state: "Johor", country: "Malaysia", countryCode: "MY" },
  { city: "Jakarta", state: "DKI Jakarta", country: "Indonesia", countryCode: "ID" },
  { city: "Bali", state: "Bali", country: "Indonesia", countryCode: "ID" },
  { city: "Surabaya", state: "East Java", country: "Indonesia", countryCode: "ID" },
  { city: "Bandung", state: "West Java", country: "Indonesia", countryCode: "ID" },
  { city: "Manila", state: "NCR", country: "Philippines", countryCode: "PH" },
  { city: "Cebu City", state: "Cebu", country: "Philippines", countryCode: "PH" },
  { city: "Davao", state: "Davao del Sur", country: "Philippines", countryCode: "PH" },
  { city: "Hanoi", state: "Hanoi", country: "Vietnam", countryCode: "VN" },
  { city: "Ho Chi Minh City", state: "HCMC", country: "Vietnam", countryCode: "VN" },
  { city: "Da Nang", state: "Da Nang", country: "Vietnam", countryCode: "VN" },
  { city: "Phnom Penh", state: "Phnom Penh", country: "Cambodia", countryCode: "KH" },
  { city: "Siem Reap", state: "Siem Reap", country: "Cambodia", countryCode: "KH" },
  { city: "Vientiane", state: "Vientiane", country: "Laos", countryCode: "LA" },
  { city: "Yangon", state: "Yangon", country: "Myanmar", countryCode: "MM" },
  { city: "Mumbai", state: "Maharashtra", country: "India", countryCode: "IN" },
  { city: "Delhi", state: "Delhi", country: "India", countryCode: "IN" },
  { city: "Bangalore", state: "Karnataka", country: "India", countryCode: "IN" },
  { city: "Hyderabad", state: "Telangana", country: "India", countryCode: "IN" },
  { city: "Chennai", state: "Tamil Nadu", country: "India", countryCode: "IN" },
  { city: "Kolkata", state: "West Bengal", country: "India", countryCode: "IN" },
  { city: "Pune", state: "Maharashtra", country: "India", countryCode: "IN" },
  { city: "Ahmedabad", state: "Gujarat", country: "India", countryCode: "IN" },
  { city: "Jaipur", state: "Rajasthan", country: "India", countryCode: "IN" },
  { city: "Goa", state: "Goa", country: "India", countryCode: "IN" },
  { city: "Kochi", state: "Kerala", country: "India", countryCode: "IN" },
  { city: "Colombo", state: "Western", country: "Sri Lanka", countryCode: "LK" },
  { city: "Dhaka", state: "Dhaka", country: "Bangladesh", countryCode: "BD" },
  { city: "Kathmandu", state: "Bagmati", country: "Nepal", countryCode: "NP" },
  { city: "Islamabad", state: "ICT", country: "Pakistan", countryCode: "PK" },
  { city: "Karachi", state: "Sindh", country: "Pakistan", countryCode: "PK" },
  { city: "Lahore", state: "Punjab", country: "Pakistan", countryCode: "PK" },
  { city: "Sydney", state: "NSW", country: "Australia", countryCode: "AU" },
  { city: "Melbourne", state: "VIC", country: "Australia", countryCode: "AU" },
  { city: "Brisbane", state: "QLD", country: "Australia", countryCode: "AU" },
  { city: "Perth", state: "WA", country: "Australia", countryCode: "AU" },
  { city: "Adelaide", state: "SA", country: "Australia", countryCode: "AU" },
  { city: "Gold Coast", state: "QLD", country: "Australia", countryCode: "AU" },
  { city: "Canberra", state: "ACT", country: "Australia", countryCode: "AU" },
  { city: "Hobart", state: "TAS", country: "Australia", countryCode: "AU" },
  { city: "Darwin", state: "NT", country: "Australia", countryCode: "AU" },
  { city: "Auckland", state: "Auckland", country: "New Zealand", countryCode: "NZ" },
  { city: "Wellington", state: "Wellington", country: "New Zealand", countryCode: "NZ" },
  { city: "Christchurch", state: "Canterbury", country: "New Zealand", countryCode: "NZ" },
  { city: "Queenstown", state: "Otago", country: "New Zealand", countryCode: "NZ" },
  { city: "Suva", state: "Central", country: "Fiji", countryCode: "FJ" },

  // ──── Middle East ────
  { city: "Dubai", state: "Dubai", country: "United Arab Emirates", countryCode: "AE" },
  { city: "Abu Dhabi", state: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE" },
  { city: "Sharjah", state: "Sharjah", country: "United Arab Emirates", countryCode: "AE" },
  { city: "Doha", state: "Doha", country: "Qatar", countryCode: "QA" },
  { city: "Riyadh", state: "Riyadh", country: "Saudi Arabia", countryCode: "SA" },
  { city: "Jeddah", state: "Makkah", country: "Saudi Arabia", countryCode: "SA" },
  { city: "Mecca", state: "Makkah", country: "Saudi Arabia", countryCode: "SA" },
  { city: "Medina", state: "Medina", country: "Saudi Arabia", countryCode: "SA" },
  { city: "Kuwait City", state: "Al Asimah", country: "Kuwait", countryCode: "KW" },
  { city: "Manama", state: "Capital", country: "Bahrain", countryCode: "BH" },
  { city: "Muscat", state: "Muscat", country: "Oman", countryCode: "OM" },
  { city: "Amman", state: "Amman", country: "Jordan", countryCode: "JO" },
  { city: "Beirut", state: "Beirut", country: "Lebanon", countryCode: "LB" },
  { city: "Tel Aviv", state: "Tel Aviv", country: "Israel", countryCode: "IL" },
  { city: "Jerusalem", state: "Jerusalem", country: "Israel", countryCode: "IL" },
  { city: "Haifa", state: "Haifa", country: "Israel", countryCode: "IL" },
  { city: "Istanbul", state: "Istanbul", country: "Turkey", countryCode: "TR" },
  { city: "Ankara", state: "Ankara", country: "Turkey", countryCode: "TR" },
  { city: "Izmir", state: "Izmir", country: "Turkey", countryCode: "TR" },
  { city: "Antalya", state: "Antalya", country: "Turkey", countryCode: "TR" },
  { city: "Tehran", state: "Tehran", country: "Iran", countryCode: "IR" },
  { city: "Baghdad", state: "Baghdad", country: "Iraq", countryCode: "IQ" },
  { city: "Erbil", state: "Erbil", country: "Iraq", countryCode: "IQ" },
  { city: "Damascus", state: "Damascus", country: "Syria", countryCode: "SY" },
  { city: "Tbilisi", state: "Tbilisi", country: "Georgia", countryCode: "GE" },
  { city: "Yerevan", state: "Yerevan", country: "Armenia", countryCode: "AM" },
  { city: "Baku", state: "Baku", country: "Azerbaijan", countryCode: "AZ" },

  // ──── Africa ────
  { city: "Cairo", state: "Cairo", country: "Egypt", countryCode: "EG" },
  { city: "Alexandria", state: "Alexandria", country: "Egypt", countryCode: "EG" },
  { city: "Casablanca", state: "Casablanca-Settat", country: "Morocco", countryCode: "MA" },
  { city: "Marrakech", state: "Marrakech-Safi", country: "Morocco", countryCode: "MA" },
  { city: "Rabat", state: "Rabat-Salé-Kénitra", country: "Morocco", countryCode: "MA" },
  { city: "Tunis", state: "Tunis", country: "Tunisia", countryCode: "TN" },
  { city: "Algiers", state: "Algiers", country: "Algeria", countryCode: "DZ" },
  { city: "Tripoli", state: "Tripoli", country: "Libya", countryCode: "LY" },
  { city: "Lagos", state: "Lagos", country: "Nigeria", countryCode: "NG" },
  { city: "Abuja", state: "FCT", country: "Nigeria", countryCode: "NG" },
  { city: "Accra", state: "Greater Accra", country: "Ghana", countryCode: "GH" },
  { city: "Kumasi", state: "Ashanti", country: "Ghana", countryCode: "GH" },
  { city: "Nairobi", state: "Nairobi", country: "Kenya", countryCode: "KE" },
  { city: "Mombasa", state: "Mombasa", country: "Kenya", countryCode: "KE" },
  { city: "Addis Ababa", state: "Addis Ababa", country: "Ethiopia", countryCode: "ET" },
  { city: "Dar es Salaam", state: "Dar es Salaam", country: "Tanzania", countryCode: "TZ" },
  { city: "Zanzibar City", state: "Zanzibar", country: "Tanzania", countryCode: "TZ" },
  { city: "Kampala", state: "Central", country: "Uganda", countryCode: "UG" },
  { city: "Kigali", state: "Kigali", country: "Rwanda", countryCode: "RW" },
  { city: "Kinshasa", state: "Kinshasa", country: "Democratic Republic of the Congo", countryCode: "CD" },
  { city: "Luanda", state: "Luanda", country: "Angola", countryCode: "AO" },
  { city: "Maputo", state: "Maputo", country: "Mozambique", countryCode: "MZ" },
  { city: "Lusaka", state: "Lusaka", country: "Zambia", countryCode: "ZM" },
  { city: "Harare", state: "Harare", country: "Zimbabwe", countryCode: "ZW" },
  { city: "Windhoek", state: "Khomas", country: "Namibia", countryCode: "NA" },
  { city: "Gaborone", state: "South-East", country: "Botswana", countryCode: "BW" },
  { city: "Cape Town", state: "Western Cape", country: "South Africa", countryCode: "ZA" },
  { city: "Johannesburg", state: "Gauteng", country: "South Africa", countryCode: "ZA" },
  { city: "Durban", state: "KwaZulu-Natal", country: "South Africa", countryCode: "ZA" },
  { city: "Pretoria", state: "Gauteng", country: "South Africa", countryCode: "ZA" },
  { city: "Dakar", state: "Dakar", country: "Senegal", countryCode: "SN" },
  { city: "Abidjan", state: "Abidjan", country: "Côte d'Ivoire", countryCode: "CI" },
  { city: "Douala", state: "Littoral", country: "Cameroon", countryCode: "CM" },
  { city: "Antananarivo", state: "Analamanga", country: "Madagascar", countryCode: "MG" },
  { city: "Port Louis", state: "Port Louis", country: "Mauritius", countryCode: "MU" },

  // ──── Mexico ────
  { city: "Mexico City", state: "CDMX", country: "Mexico", countryCode: "MX" },
  { city: "Guadalajara", state: "Jalisco", country: "Mexico", countryCode: "MX" },
  { city: "Monterrey", state: "Nuevo León", country: "Mexico", countryCode: "MX" },
  { city: "Cancún", state: "Quintana Roo", country: "Mexico", countryCode: "MX" },
  { city: "Puebla", state: "Puebla", country: "Mexico", countryCode: "MX" },
  { city: "Tijuana", state: "Baja California", country: "Mexico", countryCode: "MX" },
  { city: "León", state: "Guanajuato", country: "Mexico", countryCode: "MX" },
  { city: "Mérida", state: "Yucatán", country: "Mexico", countryCode: "MX" },
  { city: "San Miguel de Allende", state: "Guanajuato", country: "Mexico", countryCode: "MX" },
  { city: "Playa del Carmen", state: "Quintana Roo", country: "Mexico", countryCode: "MX" },
  { city: "Oaxaca", state: "Oaxaca", country: "Mexico", countryCode: "MX" },
  { city: "Puerto Vallarta", state: "Jalisco", country: "Mexico", countryCode: "MX" },

  // ──── Canada ────
  { city: "Toronto", state: "ON", country: "Canada", countryCode: "CA" },
  { city: "Montreal", state: "QC", country: "Canada", countryCode: "CA" },
  { city: "Vancouver", state: "BC", country: "Canada", countryCode: "CA" },
  { city: "Calgary", state: "AB", country: "Canada", countryCode: "CA" },
  { city: "Edmonton", state: "AB", country: "Canada", countryCode: "CA" },
  { city: "Ottawa", state: "ON", country: "Canada", countryCode: "CA" },
  { city: "Winnipeg", state: "MB", country: "Canada", countryCode: "CA" },
  { city: "Quebec City", state: "QC", country: "Canada", countryCode: "CA" },
  { city: "Hamilton", state: "ON", country: "Canada", countryCode: "CA" },
  { city: "Halifax", state: "NS", country: "Canada", countryCode: "CA" },
  { city: "Victoria", state: "BC", country: "Canada", countryCode: "CA" },
  { city: "Saskatoon", state: "SK", country: "Canada", countryCode: "CA" },
  { city: "Regina", state: "SK", country: "Canada", countryCode: "CA" },
  { city: "St. John's", state: "NL", country: "Canada", countryCode: "CA" },
  { city: "Kelowna", state: "BC", country: "Canada", countryCode: "CA" },
];

const normalizeCache = new Map<string, string>();

function normalizeString(s: string): string {
  const cached = normalizeCache.get(s);
  if (cached) return cached;
  const result = s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
  normalizeCache.set(s, result);
  return result;
}

export function searchCities(query: string, limit = 10): CityEntry[] {
  const q = normalizeString(query.trim());
  if (q.length < 2) return [];

  const parts = q.split(/[,\s]+/).filter(Boolean);
  const primary = parts[0];
  const secondary = parts.slice(1).join(" ");

  const results: { entry: CityEntry; score: number }[] = [];

  for (const entry of CITIES_DATA) {
    const cityNorm = normalizeString(entry.city);
    const stateNorm = normalizeString(entry.state);
    const countryNorm = normalizeString(entry.country);

    let score = 0;

    if (cityNorm === primary) {
      score = 100;
    } else if (cityNorm.startsWith(primary)) {
      score = 80 + (1 / cityNorm.length) * 10;
    } else if (cityNorm.includes(primary)) {
      score = 50;
    } else if (stateNorm.startsWith(primary) || countryNorm.startsWith(primary)) {
      score = 30;
    }

    if (score === 0) continue;

    if (secondary) {
      if (
        stateNorm.startsWith(secondary) ||
        countryNorm.startsWith(secondary) ||
        normalizeString(entry.countryCode).startsWith(secondary)
      ) {
        score += 20;
      }
    }

    results.push({ entry, score });
  }

  results.sort((a, b) => b.score - a.score);
  return results.slice(0, limit).map(r => r.entry);
}

export function formatCityDisplay(entry: CityEntry): string {
  return `${entry.city}, ${entry.state}, ${entry.country}`;
}
