import type { TaxStrategy, UserProfile } from "./taxflow-types";
import { TAX_RATES } from "./taxflow-rates";

function getRates(profile: UserProfile) {
  return TAX_RATES[profile.taxYear] || TAX_RATES[2026];
}

export const ALL_STRATEGIES: TaxStrategy[] = [
  {
    id: "sep_ira",
    title: "SEP-IRA Contribution",
    code: "IRC §408(k)",
    category: "Retirement",
    entityTypes: ["contractor", "llc", "sole_prop", "multiple"],
    maxBenefit: "Up to 25% of net SE income",
    how: "Contribute to a SEP-IRA before tax deadline (including extensions). Reduces SE income dollar-for-dollar. Easy to set up — no annual filing required.",
    eligible: "Any self-employed person with net profit",
    documentation: ["SEP-IRA account statement", "Contribution confirmation letter"],
    irsPub: "Publication 560",
    risk: "low",
    estimator: (p) => Math.min(getRates(p).sepIraMax, p.grossRevenue * 0.20),
  },
  {
    id: "solo_401k",
    title: "Solo 401(k) — Employee + Employer",
    code: "IRC §401(k)",
    category: "Retirement",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "multiple"],
    maxBenefit: "Employee + employer contributions combined",
    how: "Must be established by Dec 31. Can contribute more than SEP-IRA if income is under ~$140K because of employee contribution component. Employee deferral + 25% employer match.",
    eligible: "Self-employed with no full-time employees (spouse OK)",
    documentation: ["Solo 401(k) plan documents", "Contribution records"],
    irsPub: "Publication 560",
    risk: "low",
    estimator: (p) => Math.min(getRates(p).solo401kTotalMax, getRates(p).solo401kEmployeeMax + p.grossRevenue * 0.20),
  },
  {
    id: "home_office",
    title: "Home Office Deduction",
    code: "IRC §280A(c)",
    category: "Facilities",
    entityTypes: ["contractor", "llc", "sole_prop", "multiple"],
    maxBenefit: "Simplified: $1,500/yr | Regular: proportional actual expenses",
    how: "Space must be used regularly and exclusively for business. Simplified = $5/sq ft up to 300 sq ft. Regular method calculates actual home costs proportionally.",
    eligible: "Must be principal place of business",
    documentation: ["Floor plan showing office area", "Utility bills", "Mortgage/rent statements"],
    irsPub: "Publication 587",
    risk: "medium",
    auditNote: "Exclusive use test is strictly enforced. Document with photos.",
    estimator: (p) => p.hasHomeOffice ? Math.min(1500, p.homeOfficeSqft * 5) : 0,
  },
  {
    id: "vehicle_mileage",
    title: "Vehicle — Standard Mileage Rate",
    code: "IRC §162, Rev. Proc.",
    category: "Vehicle",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "multiple"],
    maxBenefit: "Per business mile at IRS rate",
    how: "Log every business mile with: date, destination, business purpose, odometer start/end. Much simpler than actual method.",
    eligible: "Must choose this method in first year of business use",
    documentation: ["Contemporaneous mileage log (date, destination, purpose, miles)"],
    irsPub: "Publication 463",
    risk: "low",
    estimator: (p) => {
      if (!p.usesVehicle) return 0;
      const estMiles = 3000 * (p.vehicleBusinessPct / 100 || 0.5);
      return estMiles * getRates(p).mileageRate;
    },
  },
  {
    id: "vehicle_actual",
    title: "Vehicle — Actual Expense Method",
    code: "IRC §162, Rev. Proc.",
    category: "Vehicle",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "multiple"],
    maxBenefit: "All actual vehicle costs × business use %",
    how: "Track gas, insurance, repairs, depreciation (MACRS or Section 179), registration. Multiply by business use percentage.",
    eligible: "Any vehicle used for business",
    documentation: ["Mileage log", "Gas receipts", "Insurance statements", "Repair receipts"],
    irsPub: "Publication 463",
    risk: "medium",
  },
  {
    id: "se_health_insurance",
    title: "Self-Employed Health Insurance Deduction",
    code: "IRC §162(l)",
    category: "Insurance",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "multiple"],
    maxBenefit: "100% of premiums (medical, dental, vision, long-term care)",
    how: "Above-the-line deduction on Schedule 1. Not subject to 7.5% AGI floor. Cannot exceed net SE income. Cannot use if eligible for employer-sponsored plan.",
    eligible: "Self-employed with net profit; not eligible for employer plan through spouse",
    documentation: ["Insurance premium statements", "Payment records"],
    irsPub: "Publication 535",
    risk: "low",
    estimator: (p) => Math.min(p.grossRevenue, 7200),
  },
  {
    id: "section_179",
    title: "Section 179 — Immediate Equipment Expensing",
    code: "IRC §179",
    category: "Equipment",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "ccorp", "multiple"],
    maxBenefit: "Full expensing in year of purchase",
    how: "Instead of depreciating equipment over 5-7 years, deduct 100% in year placed in service. Includes computers, software, office furniture, machinery.",
    eligible: "Must be used > 50% for business",
    documentation: ["Purchase receipts/invoices", "Proof of business use"],
    irsPub: "Publication 946",
    risk: "low",
    estimator: () => 5000,
  },
  {
    id: "bonus_depreciation",
    title: "Bonus Depreciation",
    code: "IRC §168(k)",
    category: "Equipment",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "ccorp", "multiple"],
    maxBenefit: "First-year bonus depreciation on qualified property",
    how: "Applies to new and used qualified property. Can be used in addition to or instead of Section 179. No income limitation like Section 179.",
    eligible: "Qualified property placed in service during the year",
    documentation: ["Purchase records", "Asset log"],
    irsPub: "Publication 946",
    risk: "low",
    estimator: (p) => 5000 * (getRates(p).bonusDepreciationPct),
  },
  {
    id: "qbi_deduction",
    title: "Qualified Business Income (QBI) Deduction",
    code: "IRC §199A",
    category: "Income Reduction",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "multi_llc", "multiple"],
    maxBenefit: "Up to 20% of qualified business income",
    how: "Pass-through businesses can deduct 20% of QBI. Phase-outs apply for high earners. Specified Service Trades (law, medicine, consulting) face additional limits.",
    eligible: "Most non-SSTB businesses under income thresholds get full deduction",
    documentation: ["Accurate profit/loss records"],
    irsPub: "Publication 535, Form 8995",
    risk: "low",
    estimator: (p) => {
      const qbi = p.grossRevenue * 0.7;
      if (p.grossRevenue <= getRates(p).qbiPhaseoutSingle) return qbi * 0.20;
      return 0;
    },
  },
  {
    id: "meals_50pct",
    title: "Business Meals — 50% Deduction",
    code: "IRC §274(n)",
    category: "Meals",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "ccorp", "multi_llc", "multiple"],
    maxBenefit: "50% of actual meal costs",
    how: "Must have a genuine business purpose. Must not be lavish. Document: who, what business was discussed, date, location, amount. Client entertainment is NOT deductible since TCJA 2017.",
    eligible: "Business meals only — not entertainment",
    documentation: ["Receipts with notes on who/what/why"],
    irsPub: "Publication 463",
    risk: "medium",
    estimator: (p) => p.grossRevenue * 0.02 * 0.5,
  },
  {
    id: "education",
    title: "Business Education & Professional Development",
    code: "IRC §162 (Reg. §1.162-5)",
    category: "Education",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "ccorp", "multiple"],
    maxBenefit: "100% of qualifying education costs",
    how: "Education that maintains or improves skills required in current trade/business. Does NOT include education to qualify for a new career. Includes courses, books, subscriptions, conferences.",
    eligible: "Must be related to current business — not career change",
    documentation: ["Course enrollment records", "Receipts", "Certificate/syllabus"],
    irsPub: "Publication 970",
    risk: "low",
    estimator: () => 2000,
  },
  {
    id: "phone_internet",
    title: "Business Portion of Phone & Internet",
    code: "IRC §162",
    category: "Utilities",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "ccorp", "multiple"],
    maxBenefit: "Business-use percentage of monthly bills",
    how: "If phone/internet is 70% business use, deduct 70% of the bill. Keep a usage log or make a reasonable good-faith estimate.",
    eligible: "All self-employed individuals",
    documentation: ["Monthly bills", "Usage log or calculation methodology"],
    irsPub: "Publication 535",
    risk: "low",
    estimator: () => 1800,
  },
  {
    id: "startup_costs",
    title: "Startup Cost Deduction",
    code: "IRC §195",
    category: "Startup",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "ccorp", "multi_llc", "multiple"],
    maxBenefit: "Up to $5,000 immediate + amortize remaining over 180 months",
    how: "Costs incurred before business opens. $5,000 immediate deduction phases out when total startup costs exceed $50,000.",
    eligible: "New businesses only — in year of opening",
    documentation: ["Pre-opening expense receipts", "Legal/formation documents"],
    irsPub: "Publication 535",
    risk: "low",
    estimator: () => 5000,
  },
  {
    id: "bad_debt",
    title: "Business Bad Debt Deduction",
    code: "IRC §166",
    category: "Losses",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "ccorp", "multiple"],
    maxBenefit: "Full amount of uncollectible accounts receivable",
    how: "Accrual-basis businesses can deduct invoices that become worthless. Must show the debt was genuine, arose from business, and is uncollectible.",
    eligible: "Accrual-basis businesses with uncollectible invoices",
    documentation: ["Original invoice", "Collection attempts", "Written-off documentation"],
    irsPub: "Publication 535",
    risk: "low",
  },
  {
    id: "rent_deduction",
    title: "Business Rent / Coworking Deduction",
    code: "IRC §162",
    category: "Facilities",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "ccorp", "multiple"],
    maxBenefit: "100% of rent paid for business space",
    how: "Office rent, coworking memberships, storage units used for business — all 100% deductible. Cleaner than home office from audit perspective.",
    eligible: "Any business with dedicated space",
    documentation: ["Lease agreement", "Rent payment records"],
    irsPub: "Publication 535",
    risk: "low",
    estimator: () => 3600,
  },
  {
    id: "s_corp_election",
    title: "S-Corp Election to Reduce SE Tax",
    code: "IRC §1362, IRC §1401",
    category: "Entity Structure",
    entityTypes: ["llc", "multi_llc", "multiple"],
    maxBenefit: "Save 15.3% SE tax on income above reasonable salary",
    how: "When you make an S-Corp election (Form 2553), you split income into: 1) Reasonable W-2 salary (subject to payroll taxes), 2) Owner distributions (NOT subject to 15.3% SE tax). Generally worth it when net profit exceeds $50K-$60K.",
    eligible: "Single or multi-member LLCs with consistent profit > $50K",
    documentation: ["Form 2553", "Payroll records", "Reasonable compensation analysis"],
    irsPub: "IRS Form 2553",
    risk: "low",
    auditNote: "Must maintain actual payroll and pay reasonable salary",
    estimator: (p) => {
      if (p.grossRevenue < 50000) return 0;
      const salary = Math.min(p.grossRevenue * 0.5, 80000);
      const distribution = p.grossRevenue - salary;
      return distribution * 0.153;
    },
  },
  {
    id: "accountable_plan",
    title: "Accountable Plan for Expense Reimbursements",
    code: "IRC §62(c), Reg. §1.62-2",
    category: "Reimbursements",
    entityTypes: ["llc", "scorp", "ccorp", "multi_llc", "multiple"],
    maxBenefit: "Reimburse yourself tax-free for business expenses",
    how: "Create a formal Accountable Plan document for your entity. Reimburse yourself for legitimate business expenses paid personally. Reimbursements are deductible to the business, NOT taxable to you, and not subject to payroll taxes.",
    eligible: "S-Corps and C-Corps primarily. LLCs taxed as partnerships also benefit.",
    documentation: ["Written Accountable Plan document", "Expense reports with receipts", "Reimbursement records"],
    irsPub: "Publication 15, Reg. §1.62-2",
    risk: "low",
    estimator: () => 5000,
  },
  {
    id: "augusta_rule",
    title: "Augusta Rule — Rent Your Home to Your Business",
    code: "IRC §280A(g)",
    category: "Income Shifting",
    entityTypes: ["llc", "scorp", "ccorp", "multi_llc", "multiple"],
    maxBenefit: "Up to $14,000+ tax-free per year (14 days × fair market rate)",
    how: "Rent your personal home to your business for up to 14 days per year. The rental income is TAX-FREE to you personally. The rental expense is deductible to your business. Must be for genuine business purposes with fair market rates.",
    eligible: "S-Corp and C-Corp owners who hold business meetings at home",
    documentation: ["Meeting agendas and minutes", "Fair market rental rate documentation", "Rental agreement"],
    irsPub: "IRC §280A(g)",
    risk: "medium",
    auditNote: "IRS has accepted this when properly documented. Must be legitimate business use.",
    estimator: () => 14000,
  },
  {
    id: "family_employment",
    title: "Hire Your Children (Under 18)",
    code: "IRC §3121(b)(3)",
    category: "Income Shifting",
    entityTypes: ["contractor", "llc", "sole_prop", "multiple"],
    maxBenefit: "Shift income at lower tax rates; children pay 0% up to standard deduction",
    how: "Wages paid to your children under 18 are exempt from Social Security, Medicare, and FUTA taxes. Deductible to your business and taxable to child at their lower rate. Work must be real, age-appropriate, and paid at fair market rate.",
    eligible: "Parent-owned sole proprietorships and LLCs; children must do real work",
    documentation: ["Job description", "Timesheets", "Pay stubs", "Bank account in child's name"],
    irsPub: "Publication 15",
    risk: "medium",
    auditNote: "IRS scrutinizes family employment; work must be genuine",
    estimator: () => 14600,
  },
  {
    id: "hsa_contribution",
    title: "Health Savings Account (HSA) Triple Tax Advantage",
    code: "IRC §223",
    category: "Health",
    entityTypes: ["contractor", "llc", "sole_prop", "scorp", "ccorp", "multiple"],
    maxBenefit: "Triple tax-advantaged savings",
    how: "Three tax benefits: 1) Contributions are tax-deductible, 2) Growth is tax-free, 3) Withdrawals for medical expenses are tax-free. Must have a High-Deductible Health Plan (HDHP). After age 65, can withdraw for ANY purpose.",
    eligible: "Anyone with HDHP coverage",
    documentation: ["HDHP insurance card", "HSA contribution records"],
    irsPub: "Publication 969",
    risk: "low",
    estimator: (p) => getRates(p).hsaSingle,
  },
  {
    id: "reasonable_compensation",
    title: "Reasonable Compensation Analysis",
    code: "IRC §162(a)(1), Rev. Rul. 74-44",
    category: "Salary Planning",
    entityTypes: ["scorp", "multiple"],
    maxBenefit: "Minimize salary = minimize payroll taxes legally",
    how: "The IRS requires S-Corp shareholder-employees to take 'reasonable compensation.' Set salary at the LOWEST reasonable level your role justifies. Everything above your salary = distributions (no SE tax).",
    eligible: "S-Corp shareholder-employees",
    documentation: ["Written compensation analysis", "Industry salary data", "W-2 records"],
    irsPub: "IRS Rev. Rul. 74-44",
    risk: "medium",
    auditNote: "Most important S-Corp compliance issue",
    estimator: (p) => {
      if (p.grossRevenue < 50000) return 0;
      const salary = Math.min(p.grossRevenue * 0.4, 80000);
      return (p.grossRevenue - salary) * 0.153;
    },
  },
  {
    id: "scorp_accountable_plan",
    title: "S-Corp Accountable Plan for Home Office, Vehicle, Phone",
    code: "IRC §62(c)",
    category: "Reimbursements",
    entityTypes: ["scorp", "multiple"],
    maxBenefit: "Convert personal expenses to pre-tax business deductions",
    how: "S-Corp shareholders cannot deduct unreimbursed business expenses on personal return (eliminated by TCJA 2017). Solution: Create an Accountable Plan where the S-Corp reimburses you for home office, vehicle, cell phone, internet, and other business expenses paid personally.",
    eligible: "S-Corp shareholder-employees",
    documentation: ["Signed Accountable Plan document", "Monthly expense reports", "Supporting receipts"],
    irsPub: "Publication 15",
    risk: "low",
    estimator: () => 8000,
  },
  {
    id: "scorp_retirement",
    title: "S-Corp Owner Retirement Strategy",
    code: "IRC §401(k), §408(k)",
    category: "Retirement",
    entityTypes: ["scorp", "multiple"],
    maxBenefit: "Up to $71,000 through Solo 401(k) based on W-2 salary",
    how: "S-Corp owners contribute to retirement plans based on W-2 salary. Solo 401(k): Employee up to $24,000 + Employer up to 25% of W-2. SEP-IRA: Up to 25% of W-2 salary only. Strategy: Set salary to maximize retirement contributions while minimizing overall payroll taxes.",
    eligible: "S-Corp shareholder-employees with W-2 salary",
    documentation: ["Plan documents", "W-2 records", "Contribution confirmations"],
    irsPub: "Publication 560",
    risk: "low",
    estimator: (p) => {
      const salary = Math.min(p.grossRevenue * 0.5, 80000);
      return Math.min(getRates(p).solo401kTotalMax, getRates(p).solo401kEmployeeMax + salary * 0.25);
    },
  },
  {
    id: "flat_tax_rate",
    title: "C-Corp Flat 21% Tax Rate Arbitrage",
    code: "IRC §11",
    category: "Entity Structure",
    entityTypes: ["ccorp", "multiple"],
    maxBenefit: "Retain earnings at 21% vs personal rates up to 37%",
    how: "C-Corps pay a flat 21% corporate tax rate on profits retained in the business. For high earners (37% bracket), this creates a 16% tax rate arbitrage. WARNING: Accumulated Earnings Tax (20% penalty) applies if earnings are accumulated without legitimate business purpose.",
    eligible: "C-Corporation owners with high personal income",
    documentation: ["Corporate tax return", "Business reinvestment plan"],
    irsPub: "IRC §11",
    risk: "medium",
    auditNote: "Requires planning to avoid double taxation on exit",
    estimator: (p) => p.grossRevenue > 200000 ? (p.grossRevenue - 100000) * 0.16 : 0,
  },
  {
    id: "ccorp_benefits",
    title: "C-Corp Fringe Benefits — 100% Deductible",
    code: "IRC §§105, 106, 119, 132",
    category: "Benefits",
    entityTypes: ["ccorp", "multiple"],
    maxBenefit: "Potentially $20,000+ in tax-free benefits annually",
    how: "C-Corp owners who are employees can receive: Medical reimbursement plan (HRA), disability insurance, group term life insurance ($50K), educational assistance ($5,250/yr), dependent care FSA ($5,000), company car, cell phone. S-Corp >2% owners cannot exclude most of these.",
    eligible: "C-Corp owner-employees",
    documentation: ["Benefit plan documents", "Reimbursement records"],
    irsPub: "Publication 15-B",
    risk: "low",
    estimator: () => 20000,
  },
  {
    id: "qsbs_exclusion",
    title: "QSBS — Qualified Small Business Stock Exclusion",
    code: "IRC §1202",
    category: "Exit Planning",
    entityTypes: ["ccorp", "multiple"],
    maxBenefit: "Exclude up to $10M in capital gains TAX FREE",
    how: "If your C-Corp qualifies: incorporated as C-Corp, gross assets < $50M, active business, stock held > 5 years. Then when you sell: up to $10 million in gains are COMPLETELY EXCLUDED from federal income tax. Most powerful tax incentive for startups.",
    eligible: "C-Corp founders with qualifying stock held 5+ years",
    documentation: ["Stock certificates", "Incorporation documents", "Asset records"],
    irsPub: "IRC §1202, Publication 550",
    risk: "low",
  },
  {
    id: "ccorp_retirement",
    title: "Defined Benefit Pension Plan",
    code: "IRC §412, §404",
    category: "Retirement",
    entityTypes: ["ccorp", "multiple"],
    maxBenefit: "Up to $275,000/year in contributions",
    how: "Defined Benefit plans allow much larger contributions than 401(k)s, especially for older business owners. Age 45: ~$80K/yr, Age 55: ~$160K/yr, Age 65: ~$275K/yr. All contributions are deductible to the corporation. Requires actuarial calculation annually.",
    eligible: "Profitable C-Corps with owner age 50+ and few employees",
    documentation: ["Plan documents", "Actuarial valuation", "Contribution records"],
    irsPub: "Publication 560",
    risk: "medium",
    auditNote: "Requires ongoing actuarial work; penalties for underfunding",
    estimator: () => 80000,
  },
];

export function getStrategiesForEntity(entityType: string): TaxStrategy[] {
  return ALL_STRATEGIES.filter(s =>
    s.entityTypes.includes(entityType as any) ||
    entityType === "multiple"
  );
}

export function getStrategyCategories(): string[] {
  return [...new Set(ALL_STRATEGIES.map(s => s.category))].sort();
}
