export type TaxCategory = "W-2" | "1099" | "Business Owner" | "Mixed";

export interface Occupation {
  id: string;
  name: string;
  category: string;
  taxCategory: TaxCategory;
}

export const OCCUPATION_CATEGORIES = [
  "Technology",
  "Healthcare",
  "Finance & Banking",
  "Legal",
  "Education",
  "Engineering",
  "Creative & Media",
  "Sales & Marketing",
  "Operations & Admin",
  "Real Estate",
  "Trades & Construction",
  "Transportation & Logistics",
  "Food & Hospitality",
  "Retail & Customer Service",
  "Government & Public Sector",
  "Science & Research",
  "Non-Profit & Social Services",
  "Agriculture & Environment",
  "Military & Defense",
  "Arts & Entertainment",
  "Freelance & Independent",
  "Business & Entrepreneurship",
  "Human Resources",
  "Insurance",
  "Manufacturing",
  "Other",
] as const;

export const OCCUPATIONS: Occupation[] = [
  // Technology
  { id: "tech-swe", name: "Software Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-swe-sr", name: "Senior Software Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-swe-staff", name: "Staff Software Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-swe-principal", name: "Principal Software Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-frontend", name: "Frontend Developer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-backend", name: "Backend Developer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-fullstack", name: "Full-Stack Developer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-mobile", name: "Mobile Developer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-ios", name: "iOS Developer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-android", name: "Android Developer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-devops", name: "DevOps Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-sre", name: "Site Reliability Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-cloud", name: "Cloud Architect", category: "Technology", taxCategory: "W-2" },
  { id: "tech-data-eng", name: "Data Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-data-sci", name: "Data Scientist", category: "Technology", taxCategory: "W-2" },
  { id: "tech-ml", name: "Machine Learning Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-ai", name: "AI Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-sec", name: "Cybersecurity Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-sec-analyst", name: "Security Analyst", category: "Technology", taxCategory: "W-2" },
  { id: "tech-qa", name: "QA Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-test-auto", name: "Test Automation Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-pm", name: "Technical Program Manager", category: "Technology", taxCategory: "W-2" },
  { id: "tech-infra", name: "Infrastructure Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-embedded", name: "Embedded Systems Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-blockchain", name: "Blockchain Developer", category: "Technology", taxCategory: "1099" },
  { id: "tech-db-admin", name: "Database Administrator", category: "Technology", taxCategory: "W-2" },
  { id: "tech-network", name: "Network Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-sys-admin", name: "Systems Administrator", category: "Technology", taxCategory: "W-2" },
  { id: "tech-it-support", name: "IT Support Specialist", category: "Technology", taxCategory: "W-2" },
  { id: "tech-cto", name: "Chief Technology Officer (CTO)", category: "Technology", taxCategory: "W-2" },
  { id: "tech-freelance-dev", name: "Freelance Developer", category: "Technology", taxCategory: "1099" },
  { id: "tech-consultant", name: "Technology Consultant", category: "Technology", taxCategory: "1099" },
  { id: "tech-game-dev", name: "Game Developer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-vr", name: "VR/AR Developer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-ui-engineer", name: "UI Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-solutions-arch", name: "Solutions Architect", category: "Technology", taxCategory: "W-2" },
  { id: "tech-product-eng", name: "Product Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-bi", name: "Business Intelligence Developer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-robotics", name: "Robotics Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-iot", name: "IoT Engineer", category: "Technology", taxCategory: "W-2" },

  // Healthcare
  { id: "health-physician", name: "Physician / Doctor (MD)", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-surgeon", name: "Surgeon", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-np", name: "Nurse Practitioner", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-rn", name: "Registered Nurse (RN)", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-lpn", name: "Licensed Practical Nurse (LPN)", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-crna", name: "Certified Registered Nurse Anesthetist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-physician-asst", name: "Physician Assistant", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-pharmacist", name: "Pharmacist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-dentist", name: "Dentist", category: "Healthcare", taxCategory: "Business Owner" },
  { id: "health-orthodontist", name: "Orthodontist", category: "Healthcare", taxCategory: "Business Owner" },
  { id: "health-optometrist", name: "Optometrist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-chiropractor", name: "Chiropractor", category: "Healthcare", taxCategory: "Business Owner" },
  { id: "health-therapist-pt", name: "Physical Therapist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-therapist-ot", name: "Occupational Therapist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-therapist-speech", name: "Speech-Language Pathologist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-therapist-mental", name: "Mental Health Therapist", category: "Healthcare", taxCategory: "1099" },
  { id: "health-psychologist", name: "Psychologist", category: "Healthcare", taxCategory: "1099" },
  { id: "health-psychiatrist", name: "Psychiatrist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-radiologist", name: "Radiologist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-pathologist", name: "Pathologist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-emt", name: "EMT / Paramedic", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-med-tech", name: "Medical Laboratory Technician", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-rad-tech", name: "Radiologic Technologist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-dietitian", name: "Registered Dietitian", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-social-worker", name: "Medical Social Worker", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-admin", name: "Healthcare Administrator", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-coder", name: "Medical Coder / Biller", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-vet", name: "Veterinarian", category: "Healthcare", taxCategory: "Business Owner" },
  { id: "health-podiatrist", name: "Podiatrist", category: "Healthcare", taxCategory: "Business Owner" },
  { id: "health-midwife", name: "Certified Nurse Midwife", category: "Healthcare", taxCategory: "W-2" },

  // Finance & Banking
  { id: "fin-analyst", name: "Financial Analyst", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-advisor", name: "Financial Advisor", category: "Finance & Banking", taxCategory: "1099" },
  { id: "fin-planner", name: "Certified Financial Planner (CFP)", category: "Finance & Banking", taxCategory: "1099" },
  { id: "fin-accountant", name: "Accountant", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-cpa", name: "CPA (Certified Public Accountant)", category: "Finance & Banking", taxCategory: "1099" },
  { id: "fin-auditor", name: "Auditor", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-tax-specialist", name: "Tax Specialist", category: "Finance & Banking", taxCategory: "1099" },
  { id: "fin-banker", name: "Banker / Bank Manager", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-loan-officer", name: "Loan Officer", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-underwriter", name: "Underwriter", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-trader", name: "Trader / Securities Trader", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-analyst-inv", name: "Investment Analyst", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-banker-inv", name: "Investment Banker", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-hedge-fund", name: "Hedge Fund Manager", category: "Finance & Banking", taxCategory: "Business Owner" },
  { id: "fin-vc", name: "Venture Capitalist", category: "Finance & Banking", taxCategory: "Business Owner" },
  { id: "fin-pe", name: "Private Equity Professional", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-compliance", name: "Compliance Officer", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-risk", name: "Risk Manager", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-credit-analyst", name: "Credit Analyst", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-actuary", name: "Actuary", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-cfo", name: "Chief Financial Officer (CFO)", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-controller", name: "Controller", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-treasurer", name: "Corporate Treasurer", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-bookkeeper", name: "Bookkeeper", category: "Finance & Banking", taxCategory: "1099" },
  { id: "fin-payroll", name: "Payroll Specialist", category: "Finance & Banking", taxCategory: "W-2" },

  // Legal
  { id: "legal-attorney", name: "Attorney / Lawyer", category: "Legal", taxCategory: "1099" },
  { id: "legal-corporate", name: "Corporate Lawyer", category: "Legal", taxCategory: "W-2" },
  { id: "legal-litigator", name: "Litigator / Trial Lawyer", category: "Legal", taxCategory: "W-2" },
  { id: "legal-prosecutor", name: "Prosecutor / Public Defender", category: "Legal", taxCategory: "W-2" },
  { id: "legal-partner", name: "Law Firm Partner", category: "Legal", taxCategory: "Business Owner" },
  { id: "legal-paralegal", name: "Paralegal", category: "Legal", taxCategory: "W-2" },
  { id: "legal-legal-asst", name: "Legal Assistant", category: "Legal", taxCategory: "W-2" },
  { id: "legal-judge", name: "Judge / Magistrate", category: "Legal", taxCategory: "W-2" },
  { id: "legal-compliance", name: "Legal Compliance Specialist", category: "Legal", taxCategory: "W-2" },
  { id: "legal-ip", name: "Intellectual Property Attorney", category: "Legal", taxCategory: "W-2" },
  { id: "legal-real-estate", name: "Real Estate Attorney", category: "Legal", taxCategory: "1099" },
  { id: "legal-tax-atty", name: "Tax Attorney", category: "Legal", taxCategory: "1099" },
  { id: "legal-notary", name: "Notary Public", category: "Legal", taxCategory: "1099" },

  // Education
  { id: "edu-teacher-k12", name: "K-12 Teacher", category: "Education", taxCategory: "W-2" },
  { id: "edu-teacher-elem", name: "Elementary School Teacher", category: "Education", taxCategory: "W-2" },
  { id: "edu-teacher-middle", name: "Middle School Teacher", category: "Education", taxCategory: "W-2" },
  { id: "edu-teacher-high", name: "High School Teacher", category: "Education", taxCategory: "W-2" },
  { id: "edu-professor", name: "College Professor", category: "Education", taxCategory: "W-2" },
  { id: "edu-adjunct", name: "Adjunct Professor", category: "Education", taxCategory: "1099" },
  { id: "edu-principal", name: "School Principal / Administrator", category: "Education", taxCategory: "W-2" },
  { id: "edu-counselor", name: "School Counselor", category: "Education", taxCategory: "W-2" },
  { id: "edu-special-ed", name: "Special Education Teacher", category: "Education", taxCategory: "W-2" },
  { id: "edu-tutor", name: "Private Tutor", category: "Education", taxCategory: "1099" },
  { id: "edu-curriculum", name: "Curriculum Developer", category: "Education", taxCategory: "W-2" },
  { id: "edu-librarian", name: "Librarian", category: "Education", taxCategory: "W-2" },
  { id: "edu-trainer", name: "Corporate Trainer", category: "Education", taxCategory: "1099" },
  { id: "edu-coach-aca", name: "Academic Coach / Advisor", category: "Education", taxCategory: "W-2" },
  { id: "edu-superintendent", name: "Superintendent", category: "Education", taxCategory: "W-2" },

  // Engineering
  { id: "eng-civil", name: "Civil Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-mech", name: "Mechanical Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-elec", name: "Electrical Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-chem", name: "Chemical Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-aero", name: "Aerospace Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-structural", name: "Structural Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-env", name: "Environmental Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-biomedical", name: "Biomedical Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-industrial", name: "Industrial Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-nuclear", name: "Nuclear Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-petroleum", name: "Petroleum Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-materials", name: "Materials Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-project-mgr", name: "Engineering Project Manager", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-process", name: "Process Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-quality", name: "Quality Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-systems", name: "Systems Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-controls", name: "Controls Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-architect", name: "Architect", category: "Engineering", taxCategory: "1099" },
  { id: "eng-urban-planner", name: "Urban Planner", category: "Engineering", taxCategory: "W-2" },

  // Creative & Media
  { id: "creative-designer-graphic", name: "Graphic Designer", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-designer-ux", name: "UX Designer", category: "Creative & Media", taxCategory: "W-2" },
  { id: "creative-designer-ui", name: "UI Designer", category: "Creative & Media", taxCategory: "W-2" },
  { id: "creative-designer-product", name: "Product Designer", category: "Creative & Media", taxCategory: "W-2" },
  { id: "creative-writer", name: "Writer / Author", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-copywriter", name: "Copywriter", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-content-writer", name: "Content Writer", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-journalist", name: "Journalist / Reporter", category: "Creative & Media", taxCategory: "W-2" },
  { id: "creative-editor", name: "Editor", category: "Creative & Media", taxCategory: "W-2" },
  { id: "creative-photographer", name: "Photographer", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-videographer", name: "Videographer", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-filmmaker", name: "Filmmaker / Director", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-animator", name: "Animator", category: "Creative & Media", taxCategory: "W-2" },
  { id: "creative-illustrator", name: "Illustrator", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-art-director", name: "Art Director", category: "Creative & Media", taxCategory: "W-2" },
  { id: "creative-social-media", name: "Social Media Manager", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-influencer", name: "Content Creator / Influencer", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-podcaster", name: "Podcaster", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-musician", name: "Musician / Recording Artist", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-interior-design", name: "Interior Designer", category: "Creative & Media", taxCategory: "1099" },

  // Sales & Marketing
  { id: "sales-rep", name: "Sales Representative", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-manager", name: "Sales Manager", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-director", name: "Sales Director", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-vp", name: "VP of Sales", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-ae", name: "Account Executive", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-am", name: "Account Manager", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-bdr", name: "Business Development Representative", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-channel", name: "Channel Sales Manager", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-manager", name: "Marketing Manager", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-director", name: "Marketing Director", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-cmo", name: "Chief Marketing Officer (CMO)", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-digital", name: "Digital Marketing Specialist", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-seo", name: "SEO Specialist", category: "Sales & Marketing", taxCategory: "1099" },
  { id: "mktg-sem", name: "SEM / PPC Specialist", category: "Sales & Marketing", taxCategory: "1099" },
  { id: "mktg-email", name: "Email Marketing Specialist", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-brand", name: "Brand Manager", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-growth", name: "Growth Marketer", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-product", name: "Product Marketer", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-pr", name: "PR Specialist / Publicist", category: "Sales & Marketing", taxCategory: "1099" },
  { id: "mktg-events", name: "Event Marketing Manager", category: "Sales & Marketing", taxCategory: "W-2" },

  // Operations & Admin
  { id: "ops-coo", name: "Chief Operating Officer (COO)", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-manager", name: "Operations Manager", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-analyst", name: "Operations Analyst", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-pm", name: "Project Manager", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-scrum", name: "Scrum Master / Agile Coach", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-exec-asst", name: "Executive Assistant", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-admin-asst", name: "Administrative Assistant", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-office-mgr", name: "Office Manager", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-biz-analyst", name: "Business Analyst", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-supply-chain", name: "Supply Chain Manager", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-procurement", name: "Procurement Specialist", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-data-analyst", name: "Data Analyst", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-virtual-asst", name: "Virtual Assistant", category: "Operations & Admin", taxCategory: "1099" },
  { id: "ops-customer-success", name: "Customer Success Manager", category: "Operations & Admin", taxCategory: "W-2" },

  // Real Estate
  { id: "re-agent", name: "Real Estate Agent", category: "Real Estate", taxCategory: "1099" },
  { id: "re-broker", name: "Real Estate Broker", category: "Real Estate", taxCategory: "Business Owner" },
  { id: "re-investor", name: "Real Estate Investor", category: "Real Estate", taxCategory: "Business Owner" },
  { id: "re-property-mgr", name: "Property Manager", category: "Real Estate", taxCategory: "1099" },
  { id: "re-appraiser", name: "Real Estate Appraiser", category: "Real Estate", taxCategory: "1099" },
  { id: "re-developer", name: "Real Estate Developer", category: "Real Estate", taxCategory: "Business Owner" },
  { id: "re-mortgage", name: "Mortgage Broker", category: "Real Estate", taxCategory: "1099" },
  { id: "re-leasing", name: "Leasing Agent", category: "Real Estate", taxCategory: "1099" },
  { id: "re-commercial", name: "Commercial Real Estate Broker", category: "Real Estate", taxCategory: "Business Owner" },
  { id: "re-title", name: "Title Officer / Escrow Officer", category: "Real Estate", taxCategory: "W-2" },

  // Trades & Construction
  { id: "trade-electrician", name: "Electrician", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-plumber", name: "Plumber", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-hvac", name: "HVAC Technician", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-carpenter", name: "Carpenter", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-welder", name: "Welder", category: "Trades & Construction", taxCategory: "W-2" },
  { id: "trade-construction-mgr", name: "Construction Manager", category: "Trades & Construction", taxCategory: "W-2" },
  { id: "trade-foreman", name: "Foreman / Site Supervisor", category: "Trades & Construction", taxCategory: "W-2" },
  { id: "trade-painter", name: "Painter / Painting Contractor", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-roofer", name: "Roofer", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-mason", name: "Bricklayer / Masonry Worker", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-landscape", name: "Landscaper", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-general-contractor", name: "General Contractor", category: "Trades & Construction", taxCategory: "Business Owner" },
  { id: "trade-mechanic", name: "Automotive Mechanic", category: "Trades & Construction", taxCategory: "W-2" },
  { id: "trade-machinist", name: "Machinist", category: "Trades & Construction", taxCategory: "W-2" },
  { id: "trade-ironworker", name: "Ironworker / Steel Worker", category: "Trades & Construction", taxCategory: "W-2" },

  // Transportation & Logistics
  { id: "trans-truck-driver", name: "Truck Driver (CDL)", category: "Transportation & Logistics", taxCategory: "1099" },
  { id: "trans-delivery", name: "Delivery Driver", category: "Transportation & Logistics", taxCategory: "1099" },
  { id: "trans-pilot", name: "Commercial Pilot", category: "Transportation & Logistics", taxCategory: "W-2" },
  { id: "trans-logistics-mgr", name: "Logistics Manager", category: "Transportation & Logistics", taxCategory: "W-2" },
  { id: "trans-dispatcher", name: "Dispatcher", category: "Transportation & Logistics", taxCategory: "W-2" },
  { id: "trans-warehouse", name: "Warehouse Manager", category: "Transportation & Logistics", taxCategory: "W-2" },
  { id: "trans-supply-chain", name: "Supply Chain Analyst", category: "Transportation & Logistics", taxCategory: "W-2" },
  { id: "trans-freight-broker", name: "Freight Broker", category: "Transportation & Logistics", taxCategory: "1099" },
  { id: "trans-rideshare", name: "Rideshare Driver (Uber/Lyft)", category: "Transportation & Logistics", taxCategory: "1099" },
  { id: "trans-bus-driver", name: "Bus Driver", category: "Transportation & Logistics", taxCategory: "W-2" },
  { id: "trans-flight-attendant", name: "Flight Attendant", category: "Transportation & Logistics", taxCategory: "W-2" },
  { id: "trans-shipping", name: "Shipping & Receiving Clerk", category: "Transportation & Logistics", taxCategory: "W-2" },

  // Food & Hospitality
  { id: "food-chef", name: "Chef / Head Chef", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-sous-chef", name: "Sous Chef", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-cook", name: "Cook", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-restaurant-owner", name: "Restaurant Owner", category: "Food & Hospitality", taxCategory: "Business Owner" },
  { id: "food-restaurant-mgr", name: "Restaurant Manager", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-server", name: "Server / Waiter", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-bartender", name: "Bartender", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-barista", name: "Barista", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-catering", name: "Catering Manager", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-pastry", name: "Pastry Chef / Baker", category: "Food & Hospitality", taxCategory: "1099" },
  { id: "food-hotel-mgr", name: "Hotel Manager", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-front-desk", name: "Front Desk Agent / Hotel Receptionist", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-concierge", name: "Concierge", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-event-planner", name: "Event Planner", category: "Food & Hospitality", taxCategory: "1099" },

  // Retail & Customer Service
  { id: "retail-manager", name: "Retail Store Manager", category: "Retail & Customer Service", taxCategory: "W-2" },
  { id: "retail-associate", name: "Retail Sales Associate", category: "Retail & Customer Service", taxCategory: "W-2" },
  { id: "retail-buyer", name: "Retail Buyer / Merchandise Planner", category: "Retail & Customer Service", taxCategory: "W-2" },
  { id: "retail-ecomm", name: "E-commerce Manager", category: "Retail & Customer Service", taxCategory: "W-2" },
  { id: "retail-cs-rep", name: "Customer Service Representative", category: "Retail & Customer Service", taxCategory: "W-2" },
  { id: "retail-cs-manager", name: "Customer Service Manager", category: "Retail & Customer Service", taxCategory: "W-2" },
  { id: "retail-cashier", name: "Cashier", category: "Retail & Customer Service", taxCategory: "W-2" },
  { id: "retail-store-owner", name: "Store / Shop Owner", category: "Retail & Customer Service", taxCategory: "Business Owner" },
  { id: "retail-visual-merch", name: "Visual Merchandiser", category: "Retail & Customer Service", taxCategory: "W-2" },
  { id: "retail-loss-prev", name: "Loss Prevention Specialist", category: "Retail & Customer Service", taxCategory: "W-2" },

  // Government & Public Sector
  { id: "gov-policy-analyst", name: "Policy Analyst", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-city-planner", name: "City / Municipal Planner", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-social-worker", name: "Social Worker", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-police", name: "Police Officer / Law Enforcement", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-firefighter", name: "Firefighter", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-federal-employee", name: "Federal Government Employee", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-state-employee", name: "State Government Employee", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-diplomat", name: "Diplomat / Foreign Service Officer", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-inspector", name: "Government Inspector / Regulator", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-politician", name: "Elected Official / Politician", category: "Government & Public Sector", taxCategory: "W-2" },

  // Science & Research
  { id: "sci-biologist", name: "Biologist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-chemist", name: "Chemist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-physicist", name: "Physicist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-geologist", name: "Geologist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-meteorologist", name: "Meteorologist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-epidemiologist", name: "Epidemiologist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-research-sci", name: "Research Scientist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-lab-tech", name: "Laboratory Technician", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-biotech", name: "Biotechnologist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-pharma", name: "Pharmaceutical Scientist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-ecologist", name: "Ecologist / Environmental Scientist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-statistician", name: "Statistician", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-economist", name: "Economist", category: "Science & Research", taxCategory: "W-2" },

  // Non-Profit & Social Services
  { id: "np-exec-director", name: "Non-Profit Executive Director", category: "Non-Profit & Social Services", taxCategory: "W-2" },
  { id: "np-program-mgr", name: "Non-Profit Program Manager", category: "Non-Profit & Social Services", taxCategory: "W-2" },
  { id: "np-fundraiser", name: "Fundraiser / Development Officer", category: "Non-Profit & Social Services", taxCategory: "W-2" },
  { id: "np-case-mgr", name: "Case Manager", category: "Non-Profit & Social Services", taxCategory: "W-2" },
  { id: "np-counselor", name: "Counselor / Crisis Counselor", category: "Non-Profit & Social Services", taxCategory: "W-2" },
  { id: "np-community-org", name: "Community Organizer", category: "Non-Profit & Social Services", taxCategory: "W-2" },
  { id: "np-grant-writer", name: "Grant Writer", category: "Non-Profit & Social Services", taxCategory: "1099" },
  { id: "np-volunteer-coord", name: "Volunteer Coordinator", category: "Non-Profit & Social Services", taxCategory: "W-2" },

  // Agriculture & Environment
  { id: "agri-farmer", name: "Farmer / Agricultural Producer", category: "Agriculture & Environment", taxCategory: "Business Owner" },
  { id: "agri-rancher", name: "Rancher", category: "Agriculture & Environment", taxCategory: "Business Owner" },
  { id: "agri-agronomist", name: "Agronomist", category: "Agriculture & Environment", taxCategory: "W-2" },
  { id: "agri-forester", name: "Forester", category: "Agriculture & Environment", taxCategory: "W-2" },
  { id: "agri-env-consultant", name: "Environmental Consultant", category: "Agriculture & Environment", taxCategory: "1099" },
  { id: "agri-wildlife", name: "Wildlife Biologist", category: "Agriculture & Environment", taxCategory: "W-2" },
  { id: "agri-food-scientist", name: "Food Scientist", category: "Agriculture & Environment", taxCategory: "W-2" },

  // Military & Defense
  { id: "mil-active-duty", name: "Active Duty Military", category: "Military & Defense", taxCategory: "W-2" },
  { id: "mil-veteran", name: "Military Veteran", category: "Military & Defense", taxCategory: "W-2" },
  { id: "mil-reservist", name: "Military Reservist / National Guard", category: "Military & Defense", taxCategory: "Mixed" },
  { id: "mil-intelligence", name: "Intelligence Analyst", category: "Military & Defense", taxCategory: "W-2" },
  { id: "mil-contractor", name: "Defense Contractor", category: "Military & Defense", taxCategory: "W-2" },
  { id: "mil-cybersecurity", name: "Military Cybersecurity Specialist", category: "Military & Defense", taxCategory: "W-2" },

  // Arts & Entertainment
  { id: "arts-actor", name: "Actor / Actress", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-dancer", name: "Dancer / Choreographer", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-visual-artist", name: "Visual Artist / Fine Artist", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-gallery-curator", name: "Gallery Curator / Art Curator", category: "Arts & Entertainment", taxCategory: "W-2" },
  { id: "arts-athlete-pro", name: "Professional Athlete", category: "Arts & Entertainment", taxCategory: "W-2" },
  { id: "arts-coach-sports", name: "Sports Coach / Trainer", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-entertainment-mgr", name: "Entertainment Manager", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-tv-host", name: "TV Host / Broadcaster", category: "Arts & Entertainment", taxCategory: "W-2" },
  { id: "arts-radio", name: "Radio DJ / Personality", category: "Arts & Entertainment", taxCategory: "W-2" },
  { id: "arts-makeup-artist", name: "Makeup Artist", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-stylist", name: "Fashion Stylist", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-comedian", name: "Comedian / Stand-Up", category: "Arts & Entertainment", taxCategory: "1099" },

  // Freelance & Independent
  { id: "freelance-consultant", name: "Independent Consultant", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-designer", name: "Freelance Designer", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-writer", name: "Freelance Writer", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-developer", name: "Freelance Developer", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-marketer", name: "Freelance Marketer", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-photographer", name: "Freelance Photographer", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-videographer", name: "Freelance Videographer", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-coach", name: "Life / Career Coach", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-translator", name: "Translator / Interpreter", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-va", name: "Virtual Assistant", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-bookkeeper", name: "Freelance Bookkeeper", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-accountant", name: "Freelance Accountant / CPA", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-analyst", name: "Freelance Data Analyst", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-tutor", name: "Freelance Tutor", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-gig-worker", name: "Gig Worker (DoorDash, TaskRabbit, etc.)", category: "Freelance & Independent", taxCategory: "1099" },

  // Business & Entrepreneurship
  { id: "biz-founder", name: "Founder / Co-Founder", category: "Business & Entrepreneurship", taxCategory: "Business Owner" },
  { id: "biz-ceo", name: "CEO / President", category: "Business & Entrepreneurship", taxCategory: "Business Owner" },
  { id: "biz-serial-entrepreneur", name: "Serial Entrepreneur", category: "Business & Entrepreneurship", taxCategory: "Business Owner" },
  { id: "biz-startup-ops", name: "Startup Operator", category: "Business & Entrepreneurship", taxCategory: "Business Owner" },
  { id: "biz-small-biz-owner", name: "Small Business Owner", category: "Business & Entrepreneurship", taxCategory: "Business Owner" },
  { id: "biz-franchise-owner", name: "Franchise Owner", category: "Business & Entrepreneurship", taxCategory: "Business Owner" },
  { id: "biz-ecomm-owner", name: "E-commerce Business Owner", category: "Business & Entrepreneurship", taxCategory: "Business Owner" },
  { id: "biz-investor", name: "Angel Investor", category: "Business & Entrepreneurship", taxCategory: "Business Owner" },
  { id: "biz-board-member", name: "Board Member / Director", category: "Business & Entrepreneurship", taxCategory: "1099" },
  { id: "biz-management-consultant", name: "Management Consultant", category: "Business & Entrepreneurship", taxCategory: "1099" },

  // Human Resources
  { id: "hr-manager", name: "HR Manager", category: "Human Resources", taxCategory: "W-2" },
  { id: "hr-director", name: "HR Director / Chief People Officer", category: "Human Resources", taxCategory: "W-2" },
  { id: "hr-recruiter", name: "Recruiter / Talent Acquisition", category: "Human Resources", taxCategory: "W-2" },
  { id: "hr-recruiter-ind", name: "Independent Recruiter", category: "Human Resources", taxCategory: "1099" },
  { id: "hr-benefits", name: "Benefits Administrator", category: "Human Resources", taxCategory: "W-2" },
  { id: "hr-training", name: "Training & Development Specialist", category: "Human Resources", taxCategory: "W-2" },
  { id: "hr-comp", name: "Compensation Analyst", category: "Human Resources", taxCategory: "W-2" },
  { id: "hr-de&i", name: "DEI Specialist", category: "Human Resources", taxCategory: "W-2" },
  { id: "hr-labor-rel", name: "Labor Relations Specialist", category: "Human Resources", taxCategory: "W-2" },

  // Insurance
  { id: "ins-agent", name: "Insurance Agent", category: "Insurance", taxCategory: "1099" },
  { id: "ins-broker", name: "Insurance Broker", category: "Insurance", taxCategory: "1099" },
  { id: "ins-adjuster", name: "Claims Adjuster", category: "Insurance", taxCategory: "W-2" },
  { id: "ins-underwriter", name: "Insurance Underwriter", category: "Insurance", taxCategory: "W-2" },
  { id: "ins-actuary", name: "Insurance Actuary", category: "Insurance", taxCategory: "W-2" },
  { id: "ins-risk-mgr", name: "Risk Manager", category: "Insurance", taxCategory: "W-2" },
  { id: "ins-life", name: "Life Insurance Specialist", category: "Insurance", taxCategory: "1099" },

  // Manufacturing
  { id: "mfg-operator", name: "Machine Operator", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-assembler", name: "Assembly Line Worker", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-quality-inspector", name: "Quality Control Inspector", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-plant-mgr", name: "Plant / Factory Manager", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-production-planner", name: "Production Planner", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-maintenance-tech", name: "Maintenance Technician", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-lean", name: "Lean / Six Sigma Specialist", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-safety-officer", name: "Safety Officer / EHS Specialist", category: "Manufacturing", taxCategory: "W-2" },

  // Additional Technology
  { id: "tech-product-mgr", name: "Product Manager", category: "Technology", taxCategory: "W-2" },
  { id: "tech-product-owner", name: "Product Owner", category: "Technology", taxCategory: "W-2" },
  { id: "tech-data-arch", name: "Data Architect", category: "Technology", taxCategory: "W-2" },
  { id: "tech-analytics-eng", name: "Analytics Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-prompt-eng", name: "Prompt Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-cyber-mgr", name: "Cybersecurity Manager", category: "Technology", taxCategory: "W-2" },
  { id: "tech-pen-tester", name: "Penetration Tester", category: "Technology", taxCategory: "W-2" },
  { id: "tech-devsecops", name: "DevSecOps Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-platform-eng", name: "Platform Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-release-eng", name: "Release Engineer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-3d-artist", name: "3D Artist / Technical Artist", category: "Technology", taxCategory: "W-2" },
  { id: "tech-gis", name: "GIS Analyst / Geospatial Developer", category: "Technology", taxCategory: "W-2" },
  { id: "tech-erp", name: "ERP Consultant (SAP/Oracle)", category: "Technology", taxCategory: "1099" },
  { id: "tech-salesforce", name: "Salesforce Developer / Admin", category: "Technology", taxCategory: "W-2" },
  { id: "tech-ciso", name: "Chief Information Security Officer (CISO)", category: "Technology", taxCategory: "W-2" },

  // Additional Healthcare
  { id: "health-dental-hygienist", name: "Dental Hygienist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-surgical-tech", name: "Surgical Technologist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-home-health-aide", name: "Home Health Aide", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-cna", name: "Certified Nursing Assistant (CNA)", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-respiratory-therapist", name: "Respiratory Therapist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-cardiac-tech", name: "Cardiovascular Technologist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-pharmacy-tech", name: "Pharmacy Technician", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-health-coach", name: "Health Coach / Wellness Coach", category: "Healthcare", taxCategory: "1099" },
  { id: "health-acupuncturist", name: "Acupuncturist", category: "Healthcare", taxCategory: "1099" },
  { id: "health-massage-therapist", name: "Massage Therapist", category: "Healthcare", taxCategory: "1099" },
  { id: "health-telehealth", name: "Telehealth Specialist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-health-informatics", name: "Health Informatics Specialist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-dermatologist", name: "Dermatologist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-neurologist", name: "Neurologist", category: "Healthcare", taxCategory: "W-2" },
  { id: "health-oncologist", name: "Oncologist", category: "Healthcare", taxCategory: "W-2" },

  // Additional Finance
  { id: "fin-wealth-mgr", name: "Wealth Manager", category: "Finance & Banking", taxCategory: "1099" },
  { id: "fin-quant-analyst", name: "Quantitative Analyst (Quant)", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-relationship-mgr", name: "Relationship Manager (Banking)", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-mortgage-advisor", name: "Mortgage Advisor", category: "Finance & Banking", taxCategory: "1099" },
  { id: "fin-tax-preparer", name: "Tax Preparer", category: "Finance & Banking", taxCategory: "1099" },
  { id: "fin-fintech", name: "FinTech Product Manager", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-crypto-analyst", name: "Cryptocurrency Analyst", category: "Finance & Banking", taxCategory: "1099" },
  { id: "fin-budget-analyst", name: "Budget Analyst", category: "Finance & Banking", taxCategory: "W-2" },
  { id: "fin-forensic-acct", name: "Forensic Accountant", category: "Finance & Banking", taxCategory: "1099" },
  { id: "fin-day-trader", name: "Day Trader", category: "Finance & Banking", taxCategory: "Business Owner" },

  // Additional Sales & Marketing
  { id: "mktg-content-strat", name: "Content Strategist", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-influencer-mktg", name: "Influencer Marketing Manager", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-affiliate", name: "Affiliate Marketer", category: "Sales & Marketing", taxCategory: "1099" },
  { id: "mktg-analytics", name: "Marketing Analytics Manager", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "mktg-comm-mgr", name: "Communications Manager", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-inside-sales", name: "Inside Sales Representative", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-outside-sales", name: "Outside Sales Representative", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-pharma-rep", name: "Pharmaceutical Sales Representative", category: "Sales & Marketing", taxCategory: "W-2" },
  { id: "sales-insurance-sales", name: "Insurance Sales Agent", category: "Sales & Marketing", taxCategory: "1099" },
  { id: "sales-car-salesperson", name: "Automotive Salesperson", category: "Sales & Marketing", taxCategory: "W-2" },

  // Additional Creative & Media
  { id: "creative-brand-designer", name: "Brand Identity Designer", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-motion-graphics", name: "Motion Graphics Designer", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-3d-modeler", name: "3D Modeler / Visual Effects Artist", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-voice-actor", name: "Voice Actor", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-scriptwriter", name: "Scriptwriter / Screenwriter", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-podcast-producer", name: "Podcast Producer", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-youtuber", name: "YouTuber", category: "Creative & Media", taxCategory: "Business Owner" },
  { id: "creative-prop-stylist", name: "Prop Stylist", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-web-designer", name: "Web Designer", category: "Creative & Media", taxCategory: "1099" },
  { id: "creative-comics-artist", name: "Comics Artist / Illustrator", category: "Creative & Media", taxCategory: "1099" },

  // Additional Engineering
  { id: "eng-surveyor", name: "Land Surveyor", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-fire-protection", name: "Fire Protection Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-acoustic", name: "Acoustical Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-telecom", name: "Telecommunications Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-marine", name: "Marine Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-geotechnical", name: "Geotechnical Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-transportation", name: "Transportation Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-safety-eng", name: "Safety Engineer", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-cost-estimator", name: "Cost Estimator", category: "Engineering", taxCategory: "W-2" },
  { id: "eng-cad-designer", name: "CAD Designer / Drafter", category: "Engineering", taxCategory: "W-2" },

  // Additional Real Estate
  { id: "re-home-inspector", name: "Home Inspector", category: "Real Estate", taxCategory: "1099" },
  { id: "re-stager", name: "Home Stager", category: "Real Estate", taxCategory: "1099" },
  { id: "re-investment-analyst", name: "Real Estate Investment Analyst", category: "Real Estate", taxCategory: "W-2" },
  { id: "re-short-term-rental", name: "Short-Term Rental Host (Airbnb/VRBO)", category: "Real Estate", taxCategory: "Business Owner" },

  // Additional Operations & Admin
  { id: "ops-logistics-coord", name: "Logistics Coordinator", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-facilities-mgr", name: "Facilities Manager", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-event-coordinator", name: "Event Coordinator", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-translation-mgr", name: "Localization Manager", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-research-analyst", name: "Research Analyst", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-legal-ops", name: "Legal Operations Manager", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-rev-ops", name: "Revenue Operations Manager", category: "Operations & Admin", taxCategory: "W-2" },
  { id: "ops-product-ops", name: "Product Operations Manager", category: "Operations & Admin", taxCategory: "W-2" },

  // Additional Trades & Construction
  { id: "trade-flooring", name: "Flooring Installer", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-drywaller", name: "Drywall Installer / Finisher", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-pool-tech", name: "Pool Technician", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-locksmith", name: "Locksmith", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-glass", name: "Glazier / Glass Installer", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-elevator-tech", name: "Elevator Technician", category: "Trades & Construction", taxCategory: "W-2" },
  { id: "trade-insulation", name: "Insulation Installer", category: "Trades & Construction", taxCategory: "1099" },
  { id: "trade-tile-setter", name: "Tile Setter", category: "Trades & Construction", taxCategory: "1099" },

  // Additional Education
  { id: "edu-instructional-designer", name: "Instructional Designer", category: "Education", taxCategory: "W-2" },
  { id: "edu-elearning-dev", name: "eLearning Developer", category: "Education", taxCategory: "1099" },
  { id: "edu-coach", name: "Executive / Leadership Coach", category: "Education", taxCategory: "1099" },
  { id: "edu-test-prep", name: "Test Prep Instructor", category: "Education", taxCategory: "1099" },
  { id: "edu-preschool-teacher", name: "Preschool / Early Childhood Teacher", category: "Education", taxCategory: "W-2" },
  { id: "edu-music-teacher", name: "Music Teacher", category: "Education", taxCategory: "1099" },
  { id: "edu-online-course", name: "Online Course Creator", category: "Education", taxCategory: "Business Owner" },

  // Additional Transportation
  { id: "trans-marine-captain", name: "Ship Captain / Marine Officer", category: "Transportation & Logistics", taxCategory: "W-2" },
  { id: "trans-railroad", name: "Railroad Worker / Conductor", category: "Transportation & Logistics", taxCategory: "W-2" },
  { id: "trans-airport-ops", name: "Airport Operations Specialist", category: "Transportation & Logistics", taxCategory: "W-2" },
  { id: "trans-customs-broker", name: "Customs Broker", category: "Transportation & Logistics", taxCategory: "1099" },
  { id: "trans-import-export", name: "Import/Export Specialist", category: "Transportation & Logistics", taxCategory: "W-2" },

  // Additional Food & Hospitality
  { id: "food-food-blogger", name: "Food Blogger / Recipe Developer", category: "Food & Hospitality", taxCategory: "1099" },
  { id: "food-personal-chef", name: "Personal Chef", category: "Food & Hospitality", taxCategory: "1099" },
  { id: "food-wine-sommelier", name: "Sommelier / Wine Specialist", category: "Food & Hospitality", taxCategory: "W-2" },
  { id: "food-food-delivery", name: "Food Delivery Driver", category: "Food & Hospitality", taxCategory: "1099" },
  { id: "food-tour-guide", name: "Tour Guide", category: "Food & Hospitality", taxCategory: "1099" },
  { id: "food-cruise-director", name: "Cruise Director / Hospitality Manager", category: "Food & Hospitality", taxCategory: "W-2" },

  // Additional Government
  { id: "gov-probation-officer", name: "Probation Officer", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-corrections-officer", name: "Corrections Officer", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-customs-officer", name: "Customs Officer / Border Patrol", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-postal-worker", name: "Postal Worker", category: "Government & Public Sector", taxCategory: "W-2" },
  { id: "gov-emergency-mgr", name: "Emergency Management Specialist", category: "Government & Public Sector", taxCategory: "W-2" },

  // Additional Business & Entrepreneurship
  { id: "biz-product-manager", name: "Product Manager (B2B/B2C)", category: "Business & Entrepreneurship", taxCategory: "W-2" },
  { id: "biz-strategy-consultant", name: "Strategy Consultant", category: "Business & Entrepreneurship", taxCategory: "1099" },
  { id: "biz-operations-consultant", name: "Operations Consultant", category: "Business & Entrepreneurship", taxCategory: "1099" },
  { id: "biz-executive-director", name: "Executive Director", category: "Business & Entrepreneurship", taxCategory: "W-2" },
  { id: "biz-general-manager", name: "General Manager", category: "Business & Entrepreneurship", taxCategory: "W-2" },
  { id: "biz-dropshipper", name: "Dropshipper / Online Reseller", category: "Business & Entrepreneurship", taxCategory: "Business Owner" },
  { id: "biz-day-trader", name: "Full-Time Investor / Trader", category: "Business & Entrepreneurship", taxCategory: "Business Owner" },

  // Additional Freelance
  { id: "freelance-seo", name: "Freelance SEO Consultant", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-social-media", name: "Freelance Social Media Manager", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-podcast-editor", name: "Freelance Podcast Editor", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-video-editor", name: "Freelance Video Editor", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-web-developer", name: "Freelance Web Developer", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-app-developer", name: "Freelance App Developer", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-project-mgr", name: "Freelance Project Manager", category: "Freelance & Independent", taxCategory: "1099" },
  { id: "freelance-voice-over", name: "Freelance Voice-Over Artist", category: "Freelance & Independent", taxCategory: "1099" },

  // Additional HR
  { id: "hr-people-ops", name: "People Operations Specialist", category: "Human Resources", taxCategory: "W-2" },
  { id: "hr-org-dev", name: "Organizational Development Specialist", category: "Human Resources", taxCategory: "W-2" },
  { id: "hr-executive-recruiter", name: "Executive Recruiter (Headhunter)", category: "Human Resources", taxCategory: "1099" },
  { id: "hr-hris", name: "HRIS Specialist", category: "Human Resources", taxCategory: "W-2" },

  // Additional Manufacturing
  { id: "mfg-supply-chain-eng", name: "Supply Chain Engineer", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-cnc-operator", name: "CNC Machinist / Operator", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-tooling-eng", name: "Tooling Engineer", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-3d-printing", name: "3D Printing / Additive Manufacturing Tech", category: "Manufacturing", taxCategory: "W-2" },
  { id: "mfg-textile", name: "Textile Worker / Seamstress", category: "Manufacturing", taxCategory: "W-2" },

  // Additional Science & Research
  { id: "sci-data-science-researcher", name: "Research Data Scientist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-clinical-researcher", name: "Clinical Research Coordinator", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-materials-sci", name: "Materials Scientist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-marine-biologist", name: "Marine Biologist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-neuroscientist", name: "Neuroscientist", category: "Science & Research", taxCategory: "W-2" },
  { id: "sci-astronomer", name: "Astronomer / Astrophysicist", category: "Science & Research", taxCategory: "W-2" },

  // Additional Arts & Entertainment
  { id: "arts-dj", name: "DJ", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-yoga-instructor", name: "Yoga Instructor / Fitness Trainer", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-tattoo-artist", name: "Tattoo Artist", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-nail-tech", name: "Nail Technician", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-hair-stylist", name: "Hair Stylist / Barber", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-esthetician", name: "Esthetician / Skincare Specialist", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-personal-trainer", name: "Personal Trainer", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-swim-instructor", name: "Swimming Instructor", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-children-entertainer", name: "Children's Entertainer", category: "Arts & Entertainment", taxCategory: "1099" },
  { id: "arts-wedding-planner", name: "Wedding Planner", category: "Arts & Entertainment", taxCategory: "1099" },

  // Additional Agriculture
  { id: "agri-arborist", name: "Arborist / Tree Surgeon", category: "Agriculture & Environment", taxCategory: "1099" },
  { id: "agri-beekeeping", name: "Beekeeper", category: "Agriculture & Environment", taxCategory: "Business Owner" },
  { id: "agri-sustainability", name: "Sustainability Specialist", category: "Agriculture & Environment", taxCategory: "W-2" },
  { id: "agri-solar-tech", name: "Solar Panel Installer / Technician", category: "Agriculture & Environment", taxCategory: "W-2" },
  { id: "agri-water-treatment", name: "Water Treatment Specialist", category: "Agriculture & Environment", taxCategory: "W-2" },

  // Additional Legal
  { id: "legal-mediator", name: "Mediator / Arbitrator", category: "Legal", taxCategory: "1099" },
  { id: "legal-immigration", name: "Immigration Attorney", category: "Legal", taxCategory: "W-2" },
  { id: "legal-criminal-defense", name: "Criminal Defense Attorney", category: "Legal", taxCategory: "1099" },
  { id: "legal-contract-admin", name: "Contract Administrator", category: "Legal", taxCategory: "W-2" },

  // Additional Non-Profit
  { id: "np-policy-advocacy", name: "Policy Advocate / Lobbyist", category: "Non-Profit & Social Services", taxCategory: "W-2" },
  { id: "np-ministry", name: "Minister / Religious Leader", category: "Non-Profit & Social Services", taxCategory: "W-2" },
  { id: "np-child-welfare", name: "Child Welfare Specialist", category: "Non-Profit & Social Services", taxCategory: "W-2" },

  // Additional Military
  { id: "mil-security-contractor", name: "Security Contractor / Specialist", category: "Military & Defense", taxCategory: "1099" },
  { id: "mil-law-enforcement-fed", name: "Federal Law Enforcement (FBI/DEA/ATF)", category: "Military & Defense", taxCategory: "W-2" },

  // Additional Insurance
  { id: "ins-life-health-broker", name: "Life & Health Insurance Broker", category: "Insurance", taxCategory: "1099" },
  { id: "ins-benefits-consultant", name: "Employee Benefits Consultant", category: "Insurance", taxCategory: "1099" },

  // Other
  { id: "other-student", name: "Student", category: "Other", taxCategory: "W-2" },
  { id: "other-retired", name: "Retired", category: "Other", taxCategory: "W-2" },
  { id: "other-homemaker", name: "Homemaker / Stay-at-Home Parent", category: "Other", taxCategory: "W-2" },
  { id: "other-unemployed", name: "Currently Unemployed / Job Seeking", category: "Other", taxCategory: "W-2" },
  { id: "other-not-listed", name: "Other / Not Listed", category: "Other", taxCategory: "W-2" },
];

export function getOccupationById(id: string): Occupation | undefined {
  return OCCUPATIONS.find(o => o.id === id);
}

export function getOccupationsByCategory(category: string): Occupation[] {
  return OCCUPATIONS.filter(o => o.category === category);
}

export function searchOccupations(query: string): Occupation[] {
  const q = query.toLowerCase().trim();
  if (!q) return OCCUPATIONS;
  return OCCUPATIONS.filter(
    o =>
      o.name.toLowerCase().includes(q) ||
      o.category.toLowerCase().includes(q) ||
      o.taxCategory.toLowerCase().includes(q)
  );
}
