import { Router, type IRouter } from "express";
import healthRouter from "./health";
import stocksRouter from "./stocks";
import analyzeRouter from "./analyze";
import usersRouter from "./users";
import resumesRouter from "./resumes";
import jobsRouter from "./jobs";
import kycRouter from "./kyc";
import stripeRouter from "./stripe";
import gigsRouter from "./gigs";
import taxgptRouter from "./taxgpt";
import documentAnalyzeRouter from "./document-analyze";
import alpacaRouter from "./alpaca";
import newsRouter from "./news";
import gamificationRouter from "./gamification";
import tokenRouter from "./token";
import marketingRouter from "./marketing";
import dailyContentRouter from "./dailyContent";
import authEventsRouter from "./auth-events";
import viralRouter from "./viral";
import alertsRouter from "./alerts";
import analyticsRouter from "./analytics";
import onboardingRouter from "./onboarding";
import supportRouter from "./support";
import metricsRouter from "./metrics";
import launchChecksRouter from "./launchChecks";
import zapierRouter from "./zapier";
import pushRouter from "./push";
import paperTradingRouter from "./paperTrading";
import subscribersRouter from "./subscribers";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authEventsRouter);
router.use(pushRouter);
router.use(stocksRouter);
router.use(analyzeRouter);
router.use(usersRouter);
router.use(resumesRouter);
router.use(jobsRouter);
router.use(kycRouter);
router.use(stripeRouter);
router.use(gigsRouter);
router.use(taxgptRouter);
router.use(documentAnalyzeRouter);
router.use(alpacaRouter);
router.use(newsRouter);
router.use(gamificationRouter);
router.use(tokenRouter);
router.use(marketingRouter);
router.use(dailyContentRouter);
router.use(viralRouter);
router.use(alertsRouter);
router.use(analyticsRouter);
router.use(onboardingRouter);
router.use(supportRouter);
router.use(metricsRouter);
router.use(launchChecksRouter);
router.use(zapierRouter);
router.use(paperTradingRouter);
router.use(subscribersRouter);

export default router;
